### ISSUE TITLE
What happens to production code when we add android.jetifier.ignorelist to gradle.properties?

### ISSUE THREAD

**Issue by madim** [cashapp/paparazzi#1015]
What happens to production code when we add `android.jetifier.ignorelist=android-base-common,common` to gradle.properties?

Can this lead to runtime crashes of app itself? Or does it have any other side effects?

Jetifier docs doesn't seem to have any information about `android.jetifier.ignorelist`

**Comment by jrodbx** [comment]
Jetifier is part of the Android Tools suite (Android Gradle Plugin), so unfortunately this is not a Paparazzi issue.

However, googling that property pointed me to the following Google issues on their tracker:
* https://issuetracker.google.com/issues/131207170#comment4
* https://issuetracker.google.com/issues/184622491

Hope this helps!
