### ISSUE TITLE
 Resource qualifiers: Round display does not load layout from layout-round

### ISSUE THREAD

**Issue by ko-bra** [cashapp/paparazzi#1029]
**Description**
When setting `screenRound = ScreenRound.ROUND` in DeviceConfig layouts are not loaded from `layout-round`, but from the default `layout` folder.
This might also be a layoutLib issue, but I was not sure so I decided to report here first.

**Steps to Reproduce**
1. Create a custom view with two XML files in `layout` and `layout-round` that differ
2. Use Paparazzi to take a screenshot of the view

**Expected behavior**
When `screenRound = ScreenRound.ROUND` : The layout from `layout-round` is used
When `screenRound = ScreenRound.NOTROUND`: The layout from `layout` is used

**Additional information:**
Paparazzi Version: 1.2
OS: macOS 13.1 (22C65) aarch64
Compile SDK: 31
Gradle Version: 7.5.1
Android Gradle Plugin Version: 7.4.0

**Comment by jrodbx** [comment]
@ko-bra 

1) could you provide a small sample project?
2) could you test in layout preview to confirm whether this is a layoutlib issue?

**Comment by ko-bra** [comment]
@jrodbx 

1. Sure, you can find a small sample project here: https://github.com/ko-bra/PaparazziRoundTest.
The screenshot from the test should say "Round", but does say "Square".
2. The layout preview does switch to the round layout when you change the "Device for preview" to any round device.

**Comment by ko-bra** [comment]
Hey @jrodbx ,
just wanted to check in if you could reproduce the issue with the sample project or if there is any info missing from my side?
Thanks and have a great day 😊

**Comment by ko-bra** [comment]
@jrodbx @TWiStErRob 
Is there something I can do to support here? Unfortunately this is a major problem for us, would appreciate any help! :)

**Comment by jrodbx** [comment]
Haven't look at it, but will try to get to this soon!

**Comment by ko-bra** [comment]
@jrodbx @TWiStErRob
I don't want to nag, but rather support you if possible.
This issue is business critical for us, please let me know if I can help!

**Comment by ko-bra** [comment]
@jrodbx Also reproducible with 1.3.1.
