### ISSUE TITLE
View inflation error

### ISSUE THREAD

**Issue by ming13** [cashapp/paparazzi#106]
I’m trying to work with the application module and Spek, so this is destined to fail, but anyways. Since #105 blocks me from using the Paparazzi Gradle plugin, I’m doing what the plugin does on my own.

#### `view_basic.xml`

```xml
<?xml version="1.0" encoding="utf-8"?>
<View
    xmlns:android="http://schemas.android.com/apk/res/android"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    />
```

#### `PaparazziSpec.kt`

```kotlin
describe("paparazzi") {

    val paparazzi by memoized { Paparazzi() }

    beforeEachTest {
        val resourcesFile = File("REDACTED_MODULE_PATH/build/intermediates/paparazzi/resources.txt")
        val resources =
                """
                REDACTED_MODULE_PACKAGE_NAME
                REDACTED_MODULE_PATH/build/intermediates/res/merged/debug
                """

        resourcesFile.apply {
            parentFile?.mkdirs()
            createNewFile()
            writeText(resources.trimIndent())
        }

        paparazzi.prepare(Description.createTestDescription(PaparazziSpec::class.java, "paparazzi"))
    }

    it("should work") {
        paparazzi.snapshot(paparazzi.inflate(R.layout.view_basic), "basic")
    }

    afterEachTest {
        paparazzi.close()
    }
}
```

It actually compiles but fails to proceed.

```
kotlin.TypeCastException: null cannot be cast to non-null type V
    at app.cash.paparazzi.Paparazzi.inflate(Paparazzi.kt:128)
    at PaparazziSpec$1$1$2.invoke(PaparazziSpec.kt:42)
```

I’ve explored with a debugger a bit and seems like `BridgeInflater#inflate` returns `null`

* since `bridgeContext.getRenderResources().getResolvedResource(layoutInfo)` returns `null`
* since `RenderResources#getResolvedResource` returns `null`
* since `RenderResources#getUnresolvedResource` returns `null`
* since `ResourceResolver#getUnresolvedResource` returns `null`
* since `getResourceValueMap(reference.getNamespace(), reference.getResourceType())` returns empty map

**Comment by jrodbx** [comment]
That's correct behavior at the moment, unfortunately.  This stems from how application modules compile and merge resources vs how library modules does it.  Explained here: https://github.com/cashapp/paparazzi/issues/105

**Comment by jrodbx** [comment]
Tracked in https://github.com/cashapp/paparazzi/issues/107
