### ISSUE TITLE
Snapshot output directory is incorrect for multiplatform projects

### ISSUE THREAD

**Issue by saket** [cashapp/paparazzi#1104]
**Description**
The storage directory for snapshots is hardcoded to `src/test/snapshots`. This works for Android projects, but kinda breaks for multiplatform projects where test sources are located in `src/androidUnitTest`. Could paparazzi improve this?

https://github.com/cashapp/paparazzi/blob/33963c034abdebf02ccd007ff0c4af4ed6226c4d/paparazzi-gradle-plugin/src/main/java/app/cash/paparazzi/gradle/PaparazziPlugin.kt#L128

**Additional information:**
- Paparazzi Version: 1.3.1
- Gradle Version: 8.1.1
- Android Gradle Plugin Version: 8.1.0

**Comment by JakeWharton** [comment]
#595

**Comment by saket** [comment]
Gah and I thought I've already searched through all open issues.
