### ISSUE TITLE
AlertDialog inside Scaffold fails to render

### ISSUE THREAD

**Issue by apkelly** [cashapp/paparazzi#1107]
**Description**
If I place an `AlertDialog` inside a `Scaffold` it fails to render when capturing snapshots with Paparazzi. This setup renders correctly inside the Android Studio preview panel. Remove the `Scaffold` and the `AlertDialog` renders correctly., 

**Steps to Reproduce**
```
fun TestComposable() {
    MaterialTheme {
        Scaffold(
            backgroundColor = MaterialTheme.colors.background
        ) {
            AlertDialog(
                title = {
                    Text(
                        "Title"
                    )
                },
                text = {
                    Text(
                        "Body"
                    )
                },
                onDismissRequest = {

                },
                buttons = {

                }
            )
        }
    }
}
```

**Expected behavior**
I expect to see the dialog captured as part of the screenshot (see attachments).

**Additional information:**
- Paparazzi Version: 1.3.1
- Compose UI: 1.4.3
- OS: Mac
- Android Studio: Hedgehog
- Compile SDK: 33
- Gradle Version:
- Android Gradle Plugin Version:

**Screenshots**
Android Studio Preview
<img width="404" alt="android_studio_preview" src="https://github.com/cashapp/paparazzi/assets/2559953/81a0f800-080d-4e73-8318-085cfbdbbe89">

Paparazzi output
<img width="399" alt="paparazzi_failed_snapshot" src="https://github.com/cashapp/paparazzi/assets/2559953/26a8898e-ca95-4c9c-b4aa-9e4988f96406">

**Comment by geoff-powell** [comment]
related to #1414, closing
