### ISSUE TITLE
Screenshots not showing Coil images correctly

### ISSUE THREAD

**Issue by guerrerorodrigo** [cashapp/paparazzi#1123]
**Description**
I have different tests that use `Paparazzi`.  These tests are for a custom `Icon` that use `rememberAsyncImagePainter()` and an `ImageRequest` from `Coil`. I'm following [this](https://coil-kt.github.io/coil/testing/) approach to setup the tests.

These tests live in different classes. For the sake of this sample, there are three different classes, each with the exact same test. 

After executing `./gradlew app:recordPaparazziDebug`, I get the different images for the tests. The following are the images I get:

Test #1:
![image](https://github.com/cashapp/paparazzi/assets/77965057/e0a7a698-4c72-4a34-b903-910f11fb0633)

Test #2:
![image](https://github.com/cashapp/paparazzi/assets/77965057/e0306300-7191-4cad-b125-b63ab6a814d7)

Test #3:
![image](https://github.com/cashapp/paparazzi/assets/77965057/8856d6ef-8f19-464a-a822-002f0bd1cd62)

Only the test that is executed first, shows the image. The image is missing from the other tests, even though the tests are exactly the same.

**Steps to Reproduce**
Sample project can be found [here](https://github.com/guerrerorodrigo/paparazzicoil). You can run `./gradlew app:recordPaparazziDebug` to get the images.

**Expected behavior**
All images should show the icon.

**Additional information:**
- Paparazzi Version: `1.3.1`
- OS: API 33
- Compile SDK: `33` and `34`
- Gradle Version: `8.0`, also had the issue with `8.3`
- Android Gradle Plugin Version: `8.1.1` and `8.1.2`

**Comment by mrmike** [comment]
I think this might be related to https://github.com/cashapp/paparazzi/issues/1087#issuecomment-1728303515

**Comment by guerrerorodrigo** [comment]
@mrmike I don't think it's related, since I don't use a `LazyColumn`

**Comment by yschimke** [comment]
The tests don't look exactly the same. With matching intercept logic, do they match?

**Comment by guerrerorodrigo** [comment]
> The tests don't look exactly the same. With matching intercept logic, do they match?

The three tests in https://github.com/guerrerorodrigo/paparazzicoil/tree/master/app/src/test/java/com/rodrigoguerrero/paparazzicoil are exactly the same. Same tests, testing the same `composable`. However, only the first screenshot is generated correctly.

**Comment by yschimke** [comment]
Double check. The intercept calls differ.

**Comment by guerrerorodrigo** [comment]
that makes no difference. now they are all the same, same result.

**Comment by colinrtwhite** [comment]
Hi folks I took a look at this and opened an issue on the [Coil tracker to track](https://github.com/coil-kt/coil/issues/1910). I'm not 100% sure if this is a Coil issue, a Paparazzi issue, or somewhere in-between. I added some more info in the ticket, but it possibly appears to be a timing issue.

**Comment by qonto-android-team** [comment]
I get the same result when using Parameterized Tests.

Here is an example:


```kotlin
@RunWith(TestParameterInjector::class)
@Category(ScreenshotTest::class)
class MyScreenshotTest(
    @TestParameter config: Config
) {

    enum class Config(
         val deviceConfig: DeviceConfig
    ) {
        NEXUS_4(deviceConfig = DeviceConfig.NEXUS_4),
        NEXUS_5(deviceConfig = DeviceConfig.NEXUS_5)
    }

   @get:Rule
   val paparazzi = Paparazzi(deviceConfig = config.deviceConfig)

    @Before
    fun setUp() {
        val engine = FakeImageLoaderEngine.Builder()
            .intercept("https://www.qonto.com/image.jpg", ColorDrawable(Color.RED))
            .default(ColorDrawable(Color.BLUE))
            .build()
        val imageLoader = ImageLoader.Builder(screenshotRule.context)
            .components { add(engine) }
            .build()
        Coil.setImageLoader(imageLoader)
    }

    @After
    fun after() {
        Coil.reset()
    }

    @Test
    fun inAppInterstitial() {
        val imageUrl = "https://www.qonto.com/image.jpg"
        paparazzi.snapshot {
            MyImage(
                imageUrl = imageUrl,
                contentDescription = null
            )
        }
    }
}
```

This results in only the first screenshot overriding the image while the second does not.

**Comment by ashley-figueira** [comment]
I get the same result when using Parameterized Tests.

Here is an example:


```kotlin
@RunWith(TestParameterInjector::class)
@Category(ScreenshotTest::class)
class MyScreenshotTest(
    @TestParameter config: Config
) {

    enum class Config(
         val deviceConfig: DeviceConfig
    ) {
        NEXUS_4(deviceConfig = DeviceConfig.NEXUS_4),
        NEXUS_5(deviceConfig = DeviceConfig.NEXUS_5)
    }

   @get:Rule
   val paparazzi = Paparazzi(deviceConfig = config.deviceConfig)

    @Before
    fun setUp() {
        val engine = FakeImageLoaderEngine.Builder()
            .intercept("https://www.qonto.com/image.jpg", ColorDrawable(Color.RED))
            .default(ColorDrawable(Color.BLUE))
            .build()
        val imageLoader = ImageLoader.Builder(screenshotRule.context)
            .components { add(engine) }
            .build()
        Coil.setImageLoader(imageLoader)
    }

    @After
    fun after() {
        Coil.reset()
    }

    @Test
    fun inAppInterstitial() {
        val imageUrl = "https://www.qonto.com/image.jpg"
        paparazzi.snapshot {
            MyImage(
                imageUrl = imageUrl,
                contentDescription = null
            )
        }
    }
}
```

This results in only the first screenshot overriding the image while the second does not.

**Comment by kartik-prakash** [comment]
Any updates here? This has become a huge blocker for us.

**Comment by mtzhisham** [comment]
Was able to bypass this by setting the main dispatchers to `Unconfined` in the `@Before` method, more on why here [#1087 (comment)](https://github.com/cashapp/paparazzi/issues/1087#issuecomment-1728303515)

```Kotlin
  @Before
  fun before() {
      Dispatchers.setMain(Dispatchers.Unconfined) // setting the dispatcher to Unconfined for tests
      val engine = FakeImageLoaderEngine.Builder()
          ..
  
```

**Comment by richardortiz84** [comment]
> Was able to bypass this by setting the main dispatchers to `Unconfined` in the `@Before` method, more on why here [#1087 (comment)](https://github.com/cashapp/paparazzi/issues/1087#issuecomment-1728303515)
> 
> ```kotlin
>   @Before
>   fun before() {
>       Dispatchers.setMain(Dispatchers.Unconfined) // setting the dispatcher to Unconfined for tests
>       val engine = FakeImageLoaderEngine.Builder()
>           ..
>   
> ```

After implementing this fix we were able to get a lot of screenshot tests to work correctly. Shortly after we had a few edge cases came up where the fix did not work. It would seem this fix works for simple cases where the painter is used directly in an Image. For more complex cases where the setup relies on watching the AsyncImagePainter.State it does not seem to work.

For example:

```
AnimatedContent(
    painterState,
    label = "Image Load Transition",
) { state ->
    when (state) {
        State.Empty, is State.Loading -> ImageLoadingContent()
        is State.Success -> ImageSuccessContent()
        is State.Error -> ImageErrorContent()
    }
}
```

**Comment by julioromano** [comment]
I run into this too in a `Junit.Parameterized` test that uses `Paparazzi` to screenshot some views (old fashioned views, not using compose) that use `Coil` inside.
Only the first screenshot of the series shows images loaded by Coil.

The `Dispatchers.setMain(Dispatchers.Unconfined)` workaround fixes it so far.

**Comment by geoff-powell** [comment]
Yep, looks like Coil has implemented a [fix here.](https://github.com/coil-kt/coil/issues/1910#issuecomment-2268359983) Thanks @colinrtwhite!
