### ISSUE TITLE
Tests are very noisy

### ISSUE THREAD

**Issue by ansman** [cashapp/paparazzi#1130]
**Description**
When running Compose screenshot tests there is quite a bit of noise printed to stdout and stderr.

For example:

```
WARNING: Unrecognized tag name "java-symbol" at /Users/nicklas/Library/Android/sdk/platforms/android-34/data/res/values/config_telephony.xml line 122
    Oct 06, 2023 4:29:50 PM app.cash.paparazzi.internal.resources.RepositoryLoader getResourceType
    Oct 06, 2023 4:29:46 PM app.cash.paparazzi.internal.PaparazziLogger logAndroidFramework
    INFO: Settings [3]: Can't get key animator_duration_scale from content://settings/global
```

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: macOS Somoma 
- Compile SDK: 34
- Gradle Version: 8.3
- Android Gradle Plugin Version: 8.3

**Comment by ansman** [comment]
These can mostly be suppressed by calling `LogManager.getLogManager().reset()` at the beginning of your test. This might not be ideal if you rely on `java.util.logging` for other logs.

**Comment by soshial** [comment]
I still get noisy logs on paparazzi v1.3.4

```
Aug 06, 2024 6:19:12 PM app.cash.paparazzi.internal.PaparazziLogger logAndroidFramework
INFO: Settings [3]: Can't get key animator_duration_scale from content://settings/global
```

**Comment by LMart15** [comment]
I get similarly noisy logs on v1.3.4, only for a different key.

```
Aug 12, 2024 12:56:36 PM app.cash.paparazzi.internal.PaparazziLogger logAndroidFramework
INFO: Settings [3]: Can't get key settings_auto_text_wrapping from content://settings/global
```
