### ISSUE TITLE
verfiy with confidence  ratio 

### ISSUE THREAD

**Issue by aplha98** [cashapp/paparazzi#1182]
accept diff by 10%

**Comment by TWiStErRob** [comment]
Change the default 0.1%:

https://github.com/cashapp/paparazzi/blob/d146c9739e3f434ef0c196061ce66e26ba20bff5/paparazzi/src/main/java/app/cash/paparazzi/Paparazzi.kt#L95

to 10% with `Paparazzi(maxPercentDifference = 10.0)`
