### ISSUE TITLE
TrustAllX509TrustManager Lint error introduced with Paparazzi lib version 1.2.0

### ISSUE THREAD

**Issue by HarisHoulis** [cashapp/paparazzi#1184]
**Description**
Hi,

We recently applied to a test-helper module, part of our Android project, the [Paparazzi library dependency](https://mvnrepository.com/artifact/app.cash.paparazzi/paparazzi/1.3.1).

Before that, we were using only the [Paparazzi Gradle plugin](https://mvnrepository.com/artifact/app.cash.paparazzi/paparazzi-gradle-plugin/1.3.1) to test our `Composable`s.

After running `lintDebug`, we noticed the `TrustAllX509TrustManager` error popping as a result of the above, newly added dependency.

⚠️ This occurs with the latest version as well (`1.3.1`).

⚠️ Setting the `warningsAsErrors` to `false` doesn't trigger that error.

**Steps to Reproduce**
1. Checkout [this](https://github.com/HarisHoulis/TrustAllX509TrustManager/tree/main) demo project
2. Execute the task `lintDebug`
3. Be presented with the aforementioned error (see stacktrace [here](https://github.com/HarisHoulis/TrustAllX509TrustManager/tree/main#trustallx509trustmanager))

**Expected behavior**
Not receiving the `TrustAllX509TrustManager` error when we don't directly use it in our code (i.e. as a transient dependency).

**Additional information:**
- Paparazzi Version: `1.3.1`
- OS: MacOS Ventura `13.6.2`
- Compile SDK: `34`
- Gradle Version: `8.5.0`
- Android Gradle Plugin Version: `8.2.0`

**Comment by jrodbx** [comment]
Unfortunately, this is a lint issue (not a Paparazzi issue) and will occur with any library that bundled/references TrustAllX509TrustManager/bouncycastle.  The project references BouncyCastle via sdk-common.

```
$ ./gradlew sample:dependencies

+--- project :paparazzi
|    +--- com.android.tools:sdk-common:31.1.2
|    |    +--- org.bouncycastle:bcpkix-jdk15on:1.67
|    |    |    \--- org.bouncycastle:bcprov-jdk15on:1.67
|    |    +--- org.bouncycastle:bcprov-jdk15on:1.67
```

The workaround is to create a Lint baseline for the test-helper module which ignores this Lint issue: https://googlesamples.github.io/android-custom-lint-rules/usage/baselines.md.html
