### ISSUE TITLE
Loading string resource with getText missing markup

### ISSUE THREAD

**Issue by tynn** [cashapp/paparazzi#1213]
**Description**
The resources fail to load with markup attached, as reported in https://github.com/cashapp/paparazzi/issues/763

While the issue is fixed and released in Android Studio Hedgehog, I was wondering if/when Paparazzi will include this fix

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: MacOS
- Compile SDK: 34
- Gradle Version: 8.5
- Android Gradle Plugin Version: 8.2.1

**Comment by TWiStErRob** [comment]
Layoutlib is on Giraffe right now: https://github.com/cashapp/paparazzi/blob/master/gradle/libs.versions.toml#L17

The fix should be included when this dependency is bumped.
