### ISSUE TITLE
Typo on the 1.3.2 release

### ISSUE THREAD

**Issue by loutry** [cashapp/paparazzi#1233]
Opening a bug as I'm not sure where to report this.

The [1.3.2 release](https://github.com/cashapp/paparazzi/releases/tag/1.3.2) snippet note has a typo so it currently raise a Type mismatch. Required: Class<TypeVariable(T)!> Found: TargetJvmEnvironment.

```diff
subprojects {
  plugins.withId("app.cash.paparazzi") {
    // Defer until afterEvaluate so that testImplementation is created by Android plugin.
    afterEvaluate {
      dependencies.constraints {
        add("testImplementation", "com.google.guava:guava") {
          attributes {
            attribute(
              TargetJvmEnvironment.TARGET_JVM_ENVIRONMENT_ATTRIBUTE,
-              objects.named(TargetJvmEnvironment TargetJvmEnvironment.STANDARD_JVM)
+              objects.named(TargetJvmEnvironment::class, TargetJvmEnvironment.STANDARD_JVM)
            )
          }
          because("LayoutLib and sdk-common depend on Guava's -jre published variant." +
            "See https://github.com/cashapp/paparazzi/issues/906.")
        }
      }
    }
  }
}
```

Nothing too hard to solve, but it will be cool if you could edit the release instruction :)

Thanks in advance!

And thanks for the release 🎉

**Comment by jrodbx** [comment]
@loutry As @TWiStErRob mentioned, that's the correct syntax for Groovy.  That being said, I've added a little more clarification to the release notes to call that out.  Thanks!

**Comment by loutry** [comment]
make sense! thanks for the quick feedback
