### ISSUE TITLE
Compose View with VisualTransformation does not record properly

### ISSUE THREAD

**Issue by pedromillan** [cashapp/paparazzi#1242]
**Description**
I'm trying to record snapshots in a Compose view that uses a custom `VisualTransformation` to give some styles to a `BasicTextField` text.
The output images do not include the style in the text and leaves the space empty. In the previews, the text is styled.

**Steps to Reproduce**
1. Create a composable `BasicTextField`

```

 BasicTextField(
        ...
        singleLine = true,
        modifier = Modifier.width(IntrinsicSize.Min),
        visualTransformation = DoubleVisualTransformation(decimalStyle,fractionalStyle),
        value = amount,
        keyboardOptions = KeyboardOptions(keyboardType = KeyboardType.Number),
        onValueChange = { text -> processAmount(text) },
        ...
    )

```
2.  Create custom VisualTransformation:
```
class DoubleVisualTransformation(private val decimalStyle: SpanStyle, private val fractionalStyle: SpanStyle
) : VisualTransformation {
    override fun filter(text: AnnotatedString) = TransformedText(
        buildAmountAnnotatedString(text.toString()),
        OffsetMapping.Identity
    )

   private fun buildAmountAnnotatedString(text: String): AnnotatedString {
        val builder = AnnotatedString.Builder()
        when (text.contains(".")) {
            false -> builder.withStyle(style = decimalStyle) { append(text.ifEmpty { " " }) }
            true -> {
                val groups = text.split(".")
                val decimal: String = groups[0]
                builder.withStyle(style = decimalStyle) {
                    append(decimal)
                }
                val fractional: String? = groups.getOrNull(1)
                fractional?.let {
                    builder.withStyle(style = fractionalStyle) {
                        append(" ")
                        append(fractional.toString())
                    }
                }
            }
        }
        return builder.toAnnotatedString()
    }
}

```
3. Run `recordPaparazziDebug` in your module
4. The output screenshots does not include text styled and instead they don't display the text at all

**Expected behavior**
The output screenshots include the desired styled

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: MacOs 14.2.1
- Compile SDK: 33
- Gradle Version: 8.2.1

**Comment by jrodbx** [comment]
@pedromillan just making sure, the first snippet refers to DoubleVisualTransformation while the second refers to AmountVisualTransformation.  will swapping the first for the second still results in a suitable repro?

**Comment by pedromillan** [comment]
Hi @jrodbx, thanks for replying. Sorry, yes, yes, both are referring to the same visual transformation, I updated the naming now

**Comment by BrianGardnerAtl** [comment]
Hey @pedromillan I made a test project while checking this out and the transformations applied in the screenshots. I see you marked paparazzi version 1.3.1, could you please try version 1.3.2 and let me know the results? I'd like to track down what the difference is between our setups. Thanks!

**Comment by jrodbx** [comment]
@pedromillan are you able to confirm whether 1.3.2 has solved this issue?

**Comment by pedromillan** [comment]
Hello! We have some issues updating versions, I will be back to you as soon as I can check it in the new version. Sorry and thanks for the help!

**Comment by jrodbx** [comment]
Closing as fixed.  @pedromillan please file another issue (linking to this one) if you spot a regression.  Closes https://github.com/cashapp/paparazzi/pull/1256.
