### ISSUE TITLE
Update LayoutLib to use the new rendering engine

### ISSUE THREAD

**Issue by saket** [cashapp/paparazzi#127]
Android Studio's has a new experimental layout preview engine backed by skia/libhwui that apparently brings in many improvements including [better rendering of spans](https://issuetracker.google.com/issues/153831966). It'd be great if paparazzi could be updated to use a newer build of layoutlib.

**Comment by mattmook** [comment]
Duplicate of #110

**Comment by saket** [comment]
Closing this, let's use that issue.
