### ISSUE TITLE
Build failure Could not find com.android.tools.build:gradle:8.1.1.

### ISSUE THREAD

**Issue by Vivekban** [cashapp/paparazzi#1294]
**Description**
When adding stable Paparazzi dependency, my build failed 

```
Could not resolve all files for configuration ':classpath'.
   > Could not find com.android.tools.build:gradle:8.1.1.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/android/tools/build/gradle/8.1.1/gradle-8.1.1.pom
     Required by:
         project : > app.cash.paparazzi:app.cash.paparazzi.gradle.plugin:1.3.2 > app.cash.paparazzi:paparazzi-gradle-plugin:1.3.2
   > Could not find com.android.tools:sdk-common:31.1.2.
     Searched in the following locations:
       - https://plugins.gradle.org/m2/com/android/tools/sdk-common/31.1.2/sdk-common-31.1.2.pom
     Required by:
         project : > app.cash.paparazzi:app.cash.paparazzi.gradle.plugin:1.3.2 > app.cash.paparazzi:paparazzi-gradle-plugin:1.3.2`

```

**Steps to Reproduce**
Provide a sample project, failing test, or steps to reproduce.

**Expected behavior**

**Additional information:**
- Paparazzi Version: 1.3.2
- OS: MAC OS
- Compile SDK:  34
- Gradle Version: 8.4
- Android Gradle Plugin Version: 8.2.2

**Screenshots**

**Comment by jrodbx** [comment]
This error is saying that your project is unable to find android tools-specific dependencies, which has nothing to do with Paparazzi.  

Given the subsection under "Searched in the following locations", my guess is that your buildscript classpath is missing the google() repository, which hosts those dependencies.  For more, see https://github.com/cashapp/paparazzi?tab=readme-ov-file#releases.
