### ISSUE TITLE
`unsafeUpdateConfig` doesn't update `renderingMode`

### ISSUE THREAD

**Issue by shorner5** [cashapp/paparazzi#1352]
**Description**
When Paparazzi is initialized with `RenderingMode.NORMAL`, calling `unsafeUpdateConfig` with `RenderingMode.SHRINK` doesn't work. I think the issue is that `unsafeUpdateConfig` doesn't update `contentRoot`:

```
  private val contentRoot = """
        |<?xml version="1.0" encoding="utf-8"?>
        |<${if (hasComposeRuntime) "app.cash.paparazzi.internal.ComposeViewAdapter" else "FrameLayout"}
        |     xmlns:android="http://schemas.android.com/apk/res/android"
        |              android:layout_width="${if (renderingMode.horizAction == RenderingMode.SizeAction.SHRINK) "wrap_content" else "match_parent"}"
        |              android:layout_height="${if (renderingMode.vertAction == RenderingMode.SizeAction.SHRINK) "wrap_content" else "match_parent"}"/>
  """.trimMargin()
```

**Steps to Reproduce**
Run this test:
```
import app.cash.paparazzi.DeviceConfig
import app.cash.paparazzi.Paparazzi
import com.android.ide.common.rendering.api.SessionParams
import com.sxmp.uitoolkit.primitive.Text
import org.junit.Rule
import org.junit.Test

class RenderingModeTest {
    @get:Rule
    val paparazzi = Paparazzi(
        deviceConfig = DeviceConfig.PIXEL_5,
        renderingMode = SessionParams.RenderingMode.NORMAL
    )

    @Test
    fun snapshot() {
        paparazzi.unsafeUpdateConfig(renderingMode = SessionParams.RenderingMode.SHRINK)
        paparazzi.snapshot {
            Text(text = "Hello")
        }
    }
}
```

**Expected behavior**
The output should wrap content, so the image should be just the Text composable.

**Actual result**
The output is still displayed as `RenderingMode.NORMAL`:
![RenderingModeTest_snapshot](https://github.com/cashapp/paparazzi/assets/15132447/7e094899-b385-4e02-ba04-60b1a2aff0eb)

**Additional information:**
Paparazzi Version: 1.3.3
OS: MacOS
Compile SDK: 34
Gradle Version: 8.2.1
Android Gradle Plugin Version: 8.2.2

**Comment by KennyGoers** [comment]
I've noticed the same thing, if you create the instance with shrink then it works fine.
