### ISSUE TITLE
DatePickerDialog Crash when trying screenshot

### ISSUE THREAD

**Issue by xavijimenezmulet** [cashapp/paparazzi#1354]
Dear Paparazzi Team,

I wanted to express our sincere appreciation for the remarkable work you've done with the Paparazzi tool. It has been an invaluable asset to our development process, significantly enhancing our productivity and workflow.

However, we've encountered an issue with the DatePickerDialog that leads to a crash, and we were hoping you could provide some assistance. The crash is related to an unexpected resource format error. Specifically, the error message is as follows:

```
GRAVE: resources.format: Hexadecimal color expected, found Color State List for @android:color/system_bar_background_semi_transparent
java.lang.NumberFormatException: Color value 'C:/Users/xavi/AppData/Local/Android/Sdk/platforms/android-34/data/res/color/system_bar_background_semi_transparent.xml' has wrong size. Format is either#AARRGGBB, #RRGGBB, #RGB, or #ARGB
    at com.android.layoutlib.bridge.impl.ResourceHelper.getColor(ResourceHelper.java:136)
    at android.content.res.Resources_Delegate.getColor(Resources_Delegate.java:221)
    at android.content.res.Resources.getColor(Resources.java:1065)
    at com.android.internal.policy.DecorView.<init>(DecorView.java:313)
    at com.android.internal.policy.PhoneWindow.generateDecor(PhoneWindow.java:2385)
    at com.android.internal.policy.PhoneWindow.installDecor(PhoneWindow.java:2727)
    at com.android.internal.policy.PhoneWindow.getDecorView(PhoneWindow.java:2144)
    at androidx.compose.ui.window.DialogWrapper.<init>(AndroidDialog.android.kt:352)
    at androidx.compose.ui.window.AndroidDialog_androidKt.Dialog(AndroidDialog.android.kt:163)
    at androidx.compose.material3.AndroidAlertDialog_androidKt.BasicAlertDialog(AndroidAlertDialog.android.kt:157)
    at androidx.compose.material3.DatePickerDialog_androidKt.DatePickerDialog-GmEhDVc(DatePickerDialog.android.kt:75)
```

It appears that a hexadecimal color is expected, but instead, a Color State List is found at @android:color/system_bar_background_semi_transparent. This leads to a NumberFormatException due to an incorrect color value format.

We would greatly appreciate any guidance or updates you could provide to help us resolve this issue. Ensuring the stability and reliability of features like the DatePickerDialog is crucial for our development needs.

Thank you in advance for your time and assistance. We look forward to any possible solutions or workarounds you might suggest.

**Comment by geoff-powell** [comment]
Hi @xavijimenezmulet, looking at your stacktrace it seems that the issue may be targeting sdk 34. Paparazzi doesn't currently support 34 although there is work being done to fix this targeting [Iguana version of layoutlib](https://github.com/cashapp/paparazzi/pull/1314). 

When testing DatePickerDialog in material3 I was able to generate a snapshot of it using api 33. See [here](https://github.com/cashapp/paparazzi/compare/gpowell/demo-date-picker?expand=1).

Hopefully that solves the issue you are having.

**Comment by jrodbx** [comment]
Closing, per
* DatePickerDialog issue suggestion by @geoff-powell 
* Iguana supported per https://github.com/cashapp/paparazzi/pull/1314

**Comment by benwicks** [comment]
@geoff-powell How do you use API 33, just by using the Pixel 5 device? Upgrading to 1.3.4 is not an option for us right now due to #1465

Thanks

**Comment by geoff-powell** [comment]
@benwicks yes your right it looks like that API change didn't make it in the commit. I will update that sample branch but basically you can do. 

```
  @get:Rule
  val paparazzi = Paparazzi(
    environment = detectEnvironment().copy(compileSdkVersion = 33),
    maxPercentDifference = 1.0,
    deviceConfig = DeviceConfig.PIXEL_5.copy(softButtons = false),
    renderingMode = RenderingMode.SHRINK,
  )
```

And you can use 1.3.3 if you are holding off upgrading for now.

**Comment by benwicks** [comment]
Thanks, @geoff-powell. I was able to figure it out. At least on 1.3.3, it looks like the `platformDir` also needed to be updated in the copy call. I had set the rule like:
```
@get:Rule
    internal val rule = Paparazzi(
        deviceConfig = PIXEL_6,
        theme = "Theme.AppCompat",
        environment = detectEnvironment().copy(
            platformDir = "~/Library/Android/sdk/platforms/android-33",
            compileSdkVersion = 33
        )
    )
```
