### ISSUE TITLE
1.3.4-SNAPSHOT causes configuration cache error when used with Crashlytics

### ISSUE THREAD

**Issue by joharei** [cashapp/paparazzi#1369]
**Description**
After updating to 1.3.4-SNAPSHOT, I am getting an error that seems like it's related to Gradle's configuration cache and a clash with the Crashlytics plugin:
```
Configuration cache state could not be cached: field `__projectResourceDirs__` of task `:app:preparePaparazziDebugResources` of type `app.cash.paparazzi.gradle.PrepareResourcesTask`: error writing value of type 'org.gradle.api.internal.provider.DefaultListProperty'
> Failed to query the value of task ':app:mapDebugSourceSetPaths' property 'extraGeneratedResDir'.
   > Querying the mapped value of provider(java.util.Set) before task ':app:injectCrashlyticsMappingFileIdDebug' has completed is not supported
```

If I run the task without configuration cache it runs fine:
```bash
./gradlew --no-configuration-cache verifyPaparazziDebug
```

This error does not happen on 1.3.3.

**Steps to Reproduce**
1. Add the Crashlytics plugin to the project
2. Update to Paparazzi 1.3.4-SNAPSHOT
3. Run `verifyPaparazzi`

**Expected behavior**
Screenshot tests should run.

**Additional information:**
- Paparazzi Version: 1.3.4-SNAPSHOT
- OS: macOS 14.4.1
- Compile SDK: 34
- Gradle Version: 8.6
- Android Gradle Plugin Version: 8.3.1

**Comment by jrodbx** [comment]
@kevinzheng-ap i've seen similar when migrating into AGP 8 apis; mind taking a look if you have cycles?
