### ISSUE TITLE
Using View.ID to get the accessibility background color may make test unstable

### ISSUE THREAD

**Issue by mr-thierry** [cashapp/paparazzi#1372]
[RenderSettings](https://github.com/cashapp/paparazzi/blob/master/paparazzi/src/main/java/app/cash/paparazzi/accessibility/RenderSettings.kt) uses the view ID to get the next color.

But between build these ID can change, thus resulting in a different color between build. (View ID are generated at compile time)

I suggest something like using the String ID name and converting it to a integer. Or if the view doesn't have an ID, use the View classname converted to a number. This should result in more stable colors between builds.

**Comment by geoff-powell** [comment]
Hmm, currently we moved away from using `View.id` and are using a combination of `className` and `accessibilityText` ([source](https://github.com/cashapp/paparazzi/blob/809f3c1f9e2e23483e1469386f9ba24e768a87ab/paparazzi/src/main/java/app/cash/paparazzi/accessibility/AccessibilityRenderExtension.kt#L75)).
If there is an issue with this approach please provide a sample project that demonstrates the issue.

**Comment by jrodbx** [comment]
@mr-thierry: per @geoff-powell's comment, I'd bet you're using an older version.  Upgrading should fix the issue.
