### ISSUE TITLE
AssetsManager list() Method not working

### ISSUE THREAD

**Issue by emuguy1** [cashapp/paparazzi#1389]
**Description**
When using the assetsManager (accessing via paparazzi.context.assets or paparazzi.context.applicationContext.assets) I can open specific Files eg. paparazzi.context.assets.open("Config/0.json"). This works perfect but if I for example want to go over all the available jsons, as these are the configs for my screens, I currently can only use a try catch block. The reason for that is, that the **list()-method** of the AssetManager **always** returns null.

**Steps to Reproduce**
In your assets create a folder called Config. 
There place two json files in
Try opening one of the json files in a paparazzi test via open -> this works
Try let you give a list of all assets in that folder -> this does not work. Will always return null

**Expected behavior**
When calling the list() method on the asset Manager with paparazzi.context.assets.list("Config) should return an array with the string of the two json files included in the assets

**Additional information:**
- Paparazzi Version: 1.3.2
- OS: Mac OS Sonoma 14.4.1
- Compile SDK: 34
- Gradle Version: 8.3.2
- Android Gradle Plugin Version:  8.1.0

**Screenshots**

**Comment by jrodbx** [comment]
On Android platform, `android.content.Context.getAssets()` provides an AssetManager.  On layoutlib, this Context is a `BridgeContext` and it returns an instance of `android.content.res.BridgeAssetManager`.  Unfortunately, this impl does not override `android.content.res.AssetManager#list`.

We could probably add an Interceptor ([example](https://github.com/cashapp/paparazzi/blob/master/paparazzi/src/main/java/app/cash/paparazzi/internal/interceptors/ResourcesInterceptor.kt)) to bridge this temporarily, but it might be better to file this as a feature request with Google's issue tracker?

**Comment by TWiStErRob** [comment]
@jrodbx can a user of Paparazzi register the interceptor themselves?

**Comment by jrodbx** [comment]
> @jrodbx can a user of Paparazzi register the interceptor themselves? And by that I mostly mean: is there a hook at the right time where the registration will always be correct?

If you wrap the junit rule with another rule that registers the interceptor, that should work.

**Comment by emuguy1** [comment]
> > [@jrodbx](https://github.com/jrodbx) can a user of Paparazzi register the interceptor themselves? And by that I mostly mean: is there a hook at the right time where the registration will always be correct?
> 
> If you wrap the junit rule with another rule that registers the interceptor, that should work.

@jrodbx how would that actually look like. I am now at a stage, where I kinda need this.
