### ISSUE TITLE
EditModeInterceptor breaks GooglePay Ui and other AndroidViews

### ISSUE THREAD

**Issue by jamesrapadmi** [cashapp/paparazzi#1390]
**Description**
The [edit mode interceptor](https://github.com/cashapp/paparazzi/blob/cfd86299d06465c8bc895b32dd5ddf30c653008b/paparazzi/src/main/java/app/cash/paparazzi/internal/interceptors/EditModeInterceptor.kt) forces all views to have `isInEditMode()` false. This causes them to try network requests or other behaviour that is inappropriate for screenshot testing. There's currently no way to change this behaviour.

**Steps to Reproduce**
Create a preview using an AndroidView composable with a view using `isInEditMode()`, e.g. the GooglePay `com.google.pay.button.PayButton` composable
```
@Preview
@Composable
fun Example() {
    PayButton(
        onClick = {},
        allowedPaymentMethods = "DUMMY",
    )
}
```
Viewing the preview locally is fine, as `isInEditMode()` returns true. However, screenshotting this with Paparazzi doesn't work as the view tries to load the runtime behaviour.

**Expected behaviour**
I expected `isInEditMode()` to be true for all Paparazzi contexts. However, there should be a way to set this setting to avoid views loading runtime behaviour.

**Additional information:**
- Paparazzi Version: 1.3.2
- OS: macOS 14.1.2 (23B92)
- Compile SDK: 34
- Gradle Version: 8.7
- Android Gradle Plugin Version: 8.3.2

**Screenshots**
Preview in Android studio:
<img width="324" alt="Screenshot 2024-04-23 at 12 41 01" src="https://github.com/cashapp/paparazzi/assets/48325992/ff8afceb-5994-4272-ae91-7fc1d49400af">

**Comment by jrodbx** [comment]
This is by design.  Paparazzi is of the opinion that you should never want to do this.  It wants you to run your actual code! 

It's unfortunate that com.google.pay.button.PayButton bundles network logic in its UI.  We encountered a similar situation with Google's Map Composable; a suggested workaround for that can be found here: https://github.com/cashapp/paparazzi/issues/709#issuecomment-1693810857
