### ISSUE TITLE
Record only one test class

### ISSUE THREAD

**Issue by soygabimoreno** [cashapp/paparazzi#1399]
We can record all the tests inside a module with:
```
./gradlew sample:recordPaparazziDebug
```

I would like to do something like this:
```
./gradlew sample:recordPaparazziDebug --tests <package-name>.<test-class>
```

Would it be possible to record only one test class?

The outcome is to skip all unrequired records inside a module.

Thank you very much for the help! 🙂

**Comment by jrodbx** [comment]
Yes, this is supported!

`./gradlew sample:recordPaparazziDebug --tests=app.cash.paparazzi.sample.LaunchViewTest`
or even
`./gradlew sample:recordPaparazziDebug --tests=app.cash.paparazzi.sample.LaunchViewTest.pixel3_differentThemes`

```
> Task :sample:testDebugUnitTest

app.cash.paparazzi.sample.LaunchViewTest > pixel3_differentThemes PASSED
See the Paparazzi report at: file:///Users/jrod/Development/paparazzi/sample/build/reports/paparazzi/debug/index.html

BUILD SUCCESSFUL in 24s
30 actionable tasks: 29 executed, 1 from cache
```
