### ISSUE TITLE
How to wait for recomposition

### ISSUE THREAD

**Issue by karsie** [cashapp/paparazzi#1422]
**Description**
Releasenotes for 1.3.0 say: Recomposition does not happen unless lifecycle is RESUMED
However, when we record previews (in combination with Showkase), only the first composition is snapshotted.
This doesn't allow us to show dialogs for example, or components that rely on onTextLayout or onGloballyPositioned.
Whatever I tried to keep the state as resumed, it didn't work.
Any tips?

**Steps to Reproduce**
I tried adding something like this to our preview functions:
LaunchedEffect(true) {
  launch {
    delay(1000)
  }.join()
}

**Expected behavior**

**Additional information:**
- Paparazzi Version: 1.3.1
- OS: maxos
- Compile SDK: 34
- Gradle Version: 8.4
- Android Gradle Plugin Version: 8.3.2

**Screenshots**

**Comment by geoff-powell** [comment]
Seems to be related to https://github.com/cashapp/paparazzi/issues/1414
