### ISSUE TITLE
1.3.4 lost bottom button bar with showSystemUi = true (in some edge case)

### ISSUE THREAD

**Issue by TWiStErRob** [cashapp/paparazzi#1450]
**Description**
When upgrading from 1.3.3 to 1.3.4 tests with `showSystemUi` failed because of missing bottom buttons (along with some other slight rendering changes probably due to layoutlib internals). It's driving me crazy because the top bar is there!

The only thing that's changed are Paparazzi and compileSdk 34 for Paparazzi tests.
I diffed classes `Paparazzi` 1.3.3 vs `PaparazziSdk` 1.3.4 and they're essentially the same, so no clue there.

I'm using some hackery ([UsableActivityHack.kt](https://github.com/TWiStErRob/net.twisterrob.sun/blob/7e0de878120d506350b298dfc50845e67f0adb24/component/paparazzi/src/main/java/net/twisterrob/sun/test/screenshots/UsableActivityHack.kt)) actually run an `Activity` (launch activity, start it, detach content view, and snapshot it). **I'm looking for an idea where I could look to re-show the bottom nav, because I'm lost why it would disappear** when it was working fine since Paparazzi 1.0.0 in [2022](https://github.com/TWiStErRob/net.twisterrob.sun/commit/2d63ec43).

<details><summary>Steps to Reproduce</summary>

I tried reproducing in a small sample project without the hacks, but it "just works".
Not expecting you to repro, just listing for reference.

1. Clone https://github.com/TWiStErRob/net.twisterrob.sun
2. Check out f10917f38ff5d056b648d29d0908329209fe8628 (last 1.3.3 version)
3. `gradlew :feature:configuration:recordPaparazziDebug -Pnet.twisterrob.build.screenshot-tests=true`
4. Check out 7e0de878120d506350b298dfc50845e67f0adb24 (1.3.4 upgrade)
5. Make `useDeviceResolution = false` (or delete) in `component/paparazzi/src/main/java/net/twisterrob/sun/test/screenshots/PaparazziFactory.kt` > `activityPaparazzi()` so the delta looks reasonable (as screenshot below).
6. `gradlew :feature:configuration:verifyPaparazziDebug -Pnet.twisterrob.build.screenshot-tests=true`

</details>

**Expected behavior**
Buttons keep showing as part of `showSystemUi` as before.

**Additional information:**
- Paparazzi Version: 1.3.4
- OS: Linux, Windows
- Compile SDK: 34
- Gradle Version: 8.8-rc-1
- Android Gradle Plugin Version: 8.4.1

**Screenshots**
![delta-net twisterrob sun android_SunAngleWidgetConfigurationScreenshotTest_testValidSettings](https://github.com/cashapp/paparazzi/assets/2906988/a9f0232d-bce2-40b3-ab25-74dfd191f3e3)

**Comment by geoff-powell** [comment]
hmm, when looking at the 1.3.4 snapshot, I noticed that the navigation icons are being drawn, just in a `Light` theme. I'm going to take a look at your branch and make sure the default theme you are using to render the snapshot. It may have to do with a Theme change potential with the default theme.

**Comment by TWiStErRob** [comment]
Ah, cool! Thanks for looking. I'm on my phone and I see the white triangle, circle and square if I zoom in. I guess my PC might have wrong contrast setup, will double-check.

Some thoughts: why was it "working" before? Shouldn't the black bar be part of the light theme if there's a white "button" color? Note: on my phone, in light theme the bottom bar is light gray, and the buttons are gray (not white!). Also noticed the top bar not being light. These are just thoughts without investigating, but something still feels fishy.

**Comment by geoff-powell** [comment]
Agreed, I don't think it makes sense to change the snapshots. Specially going from Hedgehog version of LayoutLib to Iguana. There were some other updates to material and compose versions which might have to do with that change. Happy to take a quick look there. I know when we did the Iguana PR, the system ui color did change. 

Otherwise, I don't know if this is an issue with Paparazzi as it is reflecting LayoutLib's output in Android Studio.

**Comment by geoff-powell** [comment]
Confirmed that when opening 1.3.3 version of Paparazzi in Android Studio Hedgehog, the System UI is rendered like your previous snapshot suggests.
![image](https://github.com/cashapp/paparazzi/assets/18534850/33742f00-fdc7-45a5-981c-d9d102472191)

The version of [AppCompat 1.6.1](https://github.com/cashapp/paparazzi/blob/5764f911e8d6dc7b29ad9a39bba5ccb58f738cd1/gradle/libs.versions.toml#L23))  seems to be the same across release versions 1.3.3 and 1.3.4 of Paparazzi.

Looks like Material artifact was updated from 1.5.4 -> 1.6.7 in the 1.3.4 Paparazzi.

Unfortunately I think this is a change in layout lib and the only input I have is that snapshots should be updated. It might be worth logging an issue for Android Studio.

**Comment by geoff-powell** [comment]
Also your comment `Note: on my phone, in light theme the bottom bar is light gray, and the buttons are gray (not white!). Also noticed the top bar not being light. ` seems like that is expected and could be the bug with layoutlib
