### ISSUE TITLE
CircularProgressIndicator and BottomSheet content slightly different between mac and CI

### ISSUE THREAD

**Issue by mshearer123** [cashapp/paparazzi#1451]
**Description**
Wondering if you would have any suggestions, we have 1000's of paparazzi tests that work fine between our local machines and our CI environment. 

However with either 1.3.3 (didn't use due to a different bug) or 1.3.4, we have a couple that have some slight difference.
They seem be just with `CircularProgressIndicator` and bottom sheets, so maybe animation related.

**Steps to Reproduce**
Provide a sample project, failing test, or steps to reproduce.

**Expected behavior**

**Additional information:**
- Paparazzi Version: 1.3.4
- OS: mac M1 Sonoma 14.5 vs Linux 6.1.84-hs71.el9.x86_64 (amd64)
- Compile SDK: 34
- Gradle Version: 8.7
- Android Gradle Plugin Version: 8.4.1

**Screenshots**
![example2](https://github.com/cashapp/paparazzi/assets/2699109/4f86b9bd-1d03-41a5-b6dd-f18e5d475462)

-

-

![example1](https://github.com/cashapp/paparazzi/assets/2699109/32ac4858-9a27-48a4-b485-33f5b65e69b1)

**Comment by jrodbx** [comment]
Unfortunately, this isn't very actionable.  Please provide a repro sample.  FWIW, CashApp tests Paparazzi for regressions prior to release, so anything missed from that will greatly benefit from a community-provided repro.
