### ISSUE TITLE
Verifying and recording tests do not work when using useJUnitPlatform() test options which is required for Kotest

### ISSUE THREAD

**Issue by damonM24** [cashapp/paparazzi#1511]
**Description**
I am trying to integrate paparazzi into a project that also uses Kotest for unit tests. Kotests requires the useJUnitPlatform() testOptions. Adding this causes all paparazzi tests "No tests found for given includes...". Basically any tests that use Paparazzi are skipped.

**Steps to Reproduce**
1. Add paparazzi plugin
2. Add Kotest
3. Add useJUnitPlatform() within the testOptions of your modules build.gradle
4. Run any papparazzi tests

**Expected behavior**
Paparazzi commands such as verify and record work as intended.

**Additional information:**
- Paparazzi Version: 1.3.3
- OS:
- Compile SDK: 34
- Gradle Version: 8.2.3
- Android Gradle Plugin Version: 8.2.2

**Comment by geoff-powell** [comment]
So looking at your setup, it seems like you are trying to configure Kotest which seems to use Junit5. Paparazzi currently only works with JUnit4.

Here is an example of Kotest living alongside Paparazzi. https://github.com/jsmolinski-vivint/Paparazzi-Layout-Failures/compare/main...geoff-powell:Paparazzi-Failures-Repo:gpowell/kotest?expand=1
