### ISSUE TITLE
Paparazzi tests fail to identify regressions for certain XML layout combinations

### ISSUE THREAD

**Issue by jsmolinski-vivint** [cashapp/paparazzi#1514]
**Description**

Running Paparazzi tests against certain layouts fail to identify regressions.

For example, when a `TextView` is embedded in a `ConstraintLayout` and both views have their layout params text to `MATCH_PARENT`, changing the text in the `TextView` does not result in a test failure. 

However, if the layout params of the `TextView` are set to `WRAP_CONTENT` and the view is centered in the parent, changing the text does result in a test failure.

**Steps to Reproduce**

Here is a [sample project](https://github.com/jsmolinski-vivint/Paparazzi-Layout-Failures) with steps to reproduce listed in the README

**Expected behavior**

Changing the text in any view should result in a new screenshot being generated and a failed comparison against the previously recorded golden.

**Additional information:**

- Paparazzi Version: 1.3.4
- OS: Android 14 (API 34)
- Compile SDK: 34
- Gradle Version: 8.7
- Android Gradle Plugin Version: 8.5.0

**Comment by geoff-powell** [comment]
Thanks for logging this one! I ran your project locally and confirmed that the image generated does not change causing a false positive test pass. Take a look at this now.

**Comment by geoff-powell** [comment]
I just ran your local project and the what you are seeing is that the text diff is under the `Paparazzi.maxPercentDifference` amount (defaults to 0.1%). If you changed the text to be a longer string or set `maxPercentDifference = 0.0` you will see your tests failing as expected. 

Closing this issue.

**Comment by jsmolinski-vivint** [comment]
Ah, got it. I'm surprised that the change produced such a small difference. Thanks @geoff-powell !
