### ISSUE TITLE
Exclude invalid filename characters from snapshot files

### ISSUE THREAD

**Issue by lynnkale** [cashapp/paparazzi#1532]
Windows does not allow the following characters in filenames: `< > : " / \ | ? *` but if these values are included in test parameters, they are included in the file names as well. This causes problems if tests are created with invalid characters on a *nix system but someone tries to run them on a windows machine.

**Comment by geoff-powell** [comment]
hmm interesting, `HtmlReportWriterTest` has an exact test case for these characters to not be vaild.
`assertThat("`!#$%&*+=|\\'\"<>?/".sanitizeForFilename()).isEqualTo("_________________")`

https://github.com/cashapp/paparazzi/blob/096f6039b468329f21db387877c0b7a2f373cf77/paparazzi/src/test/java/app/cash/paparazzi/HtmlReportWriterTest.kt#L89

**Comment by geoff-powell** [comment]
I was able to repo this with a new test. https://github.com/cashapp/paparazzi/actions/runs/10356499878/job/28666472264?pr=1534

Fixing it now

**Comment by jrodbx** [comment]
@lynnkale do you have a example handy which highlights "but if these values are included in test parameters"?

Looking at TestParameterInjectorTest, I suppose using a TestParameterValuesProvider that supplies a list of Strings whose literals contain those invalid characters would be one way.  Still, I'd be curious to see your specific use case to ensure things are now fixed.

**Comment by lynnkale** [comment]
@jrodbx Most of the tests I was having issues with were using `TestParameterValuesProvider` supplying strings with invalid characters, for example `"Title | Subtitle"`. The other case was a state class with an Exception attribute. It was using `ErrorState(exception = Exception("error string"))` which was producing a file name with a colon.

I can't provide direct code examples here, unfortunately, but I'm hoping this provides enough information to verify.

Thank you!

**Comment by jrodbx** [comment]
This is now closed.  See #1534, #1553 and #1622 for relevant context.
