### ISSUE TITLE
Material 3 `ModalBottomSheet` does not display Accessibility

### ISSUE THREAD

**Issue by Jonas-I** [cashapp/paparazzi#1577]
**Description**
When using the [`ModalBottomSheet`](https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#ModalBottomSheet(kotlin.Function0,androidx.compose.ui.Modifier,androidx.compose.material3.SheetState,androidx.compose.ui.unit.Dp,androidx.compose.ui.graphics.Shape,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.unit.Dp,androidx.compose.ui.graphics.Color,kotlin.Function0,kotlin.Function0,androidx.compose.material3.ModalBottomSheetProperties,kotlin.Function1)) from Material3, the accessibility for the components inside the Bottom Sheet is not rendered. The Bottom Sheet also takes up the width of the entire image rather than width of the device.

It is possible that this issue is due to the component being a modal which overlays the main UI instead of being a part of the screen layout. Using a regular [`BottomSheetScaffold`](https://developer.android.com/reference/kotlin/androidx/compose/material3/package-summary#BottomSheetScaffold(kotlin.Function1,androidx.compose.ui.Modifier,androidx.compose.material3.BottomSheetScaffoldState,androidx.compose.ui.unit.Dp,androidx.compose.ui.unit.Dp,androidx.compose.ui.graphics.Shape,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,androidx.compose.ui.unit.Dp,androidx.compose.ui.unit.Dp,kotlin.Function0,kotlin.Boolean,kotlin.Function0,kotlin.Function1,androidx.compose.ui.graphics.Color,androidx.compose.ui.graphics.Color,kotlin.Function1)) would output the expected result.

**Steps to Reproduce**
To display the BottomSheets, we have to set the `sheetState` to have an `initialValue` of `Expanded`.

For the `ModalBottomSheet`, we can use this test:
```kotlin
class ModalBottomSheetTest {

    @get:Rule
    val paparazzi = Paparazzi(renderExtensions = setOf(AccessibilityRenderExtension()))

    @Test
    @OptIn(ExperimentalMaterial3Api::class)
    fun modalBottomSheetTest() {
        paparazzi.snapshot {
            ModalBottomSheet(
                onDismissRequest = {},
                sheetState = SheetState(
                    skipPartiallyExpanded = true,
                    density = LocalDensity.current,
                    initialValue = Expanded,
                ),
            ) {
                Text(text = "Text 2")
            }
            Text(text = "Text 1")
        }
    }
}
```

For the `BottomSheetScaffold`, we can apply a similar implementation:
```kotlin
class BottomSheetScaffoldTest {

    @get:Rule
    val paparazzi = Paparazzi(renderExtensions = setOf(AccessibilityRenderExtension()))

    @Test
    @OptIn(ExperimentalMaterial3Api::class)
    fun bottomSheetScaffold() {
        paparazzi.snapshot {
            BottomSheetScaffold(
                scaffoldState = rememberBottomSheetScaffoldState(
                    bottomSheetState = SheetState(
                        skipPartiallyExpanded = true,
                        density = LocalDensity.current,
                        initialValue = Expanded,
                    )
                ),
                sheetContent = { Text(text = "Text 2") },
            ) {
                Text(text = "Text 1")
            }
        }
    }
}
```
**Expected behavior**
We should expect to see accessibility semantics for content in the `ModalBottomSheet`. 

**Additional information:**
- Paparazzi Version: 1.3.4
- OS: MacOS
- Compile SDK: 35
- Gradle Version: 8.10
- Android Gradle Plugin Version: 8.4.2

**Screenshots**
The image below renders accessibility for only the "Text 1" component, but not "Text 2". The Bottom Sheet also takes up the whole width of the image, but is overlapped by the accessibility section.

| ModalBottomSheet |
| --- |
| <img src=https://github.com/user-attachments/assets/2c0bdada-9725-41e8-9927-41f03dbb723c/> |

| BottomSheetScaffold |
| --- |
| <img src=https://github.com/user-attachments/assets/be87d91f-1a22-43dc-aa16-1b083379a533/> |

**Comment by geoff-powell** [comment]
Fixed, thanks for reporting
