### ISSUE TITLE
Differentiate similar and different pixels in delta image

### ISSUE THREAD

**Issue by gabrielittner** [cashapp/paparazzi#1612]
The `OffByTwo` differ is currently drawing [similar pixels](https://github.com/cashapp/paparazzi/blob/master/paparazzi/src/main/java/app/cash/paparazzi/internal/OffByTwo.kt#L67) with the same rgb value as [different pixels](https://github.com/cashapp/paparazzi/blob/master/paparazzi/src/main/java/app/cash/paparazzi/internal/OffByTwo.kt#L72). This makes it hard to know which differences lead to a failure and which don't and can lead to developer confusion.

**Comment by benwicks** [comment]
What RGB value would you like to see for similar pixels? @gabrielittner @jrodbx

**Comment by jrodbx** [comment]
I'd go with different (i.e., erroneous) pixels = red, similar (i.e., passable) pixels = blue, identical pixels = as is/white.
