### ISSUE TITLE
Cannot load custom font

### ISSUE THREAD

**Issue by tudorsirbu** [cashapp/paparazzi#1616]
**Description**
Hello, 

I have tried to update from compose-bom version 2023.10.01 to 2024.01.00 and all of a sudden some of my snapshot tests (using Paparazzi) started failing. Upon inspecting the stacktrace it seems it's because it couldn't load the custom fonts we have in this project. 

I've dug through release notes and recent changes but I cannot see why that is happening. Does anyone have any clue/suggestion of what might be going on? 🤔 

The fonts are under /res/folder in the project. If I load the previews in Android Studio I can see them loaded fine. 

**Steps to Reproduce**
I have also attached an example of the stacktrace from one of the tests.

**Expected behavior**

**Additional information:**
- Paparazzi Version: 1.3.1, 1.3.3
- OS: 
- Compile SDK: 34
- Gradle Version: 8.7.0 (also the same problem on 8.5.1)

**Screenshots**
I have attached screenshots of a sample test and an extension we use to run the test.

<img width="567" alt="Screenshot 2024-10-04 at 09 16 49" src="https://github.com/user-attachments/assets/5776542d-c3b4-4d53-8d31-71dc2e0ef3b3">
<img width="787" alt="Screenshot 2024-10-04 at 09 17 19" src="https://github.com/user-attachments/assets/f16fcd0f-67a0-4fea-9cdd-241aa45a6fc9">

**Comment by tudorsirbu** [comment]
[Authentication Snapshot Tests Student Sign Up output.txt](https://github.com/user-attachments/files/17255503/Authentication.Snapshot.Tests.Student.Sign.Up.output.txt)

**Comment by cbruegg** [comment]
Paparazzi 1.3.5-SNAPSHOT has some fixes regarding font loading from my understanding, you could try it

**Comment by jrodbx** [comment]
@tudorsirbu thanks for the issue.  As @cbruegg mentions, https://github.com/cashapp/paparazzi/pull/1586 landed which should fix this issue.  Can you try the snapshot (instructions on the README) and see if that helps?

However, if the issue persists, please provide a sample project that serves as a [Minimal Reproducible Example](https://stackoverflow.com/help/minimal-reproducible-example); it'll help maintainers prioritize what bugs get fixed sooner.
