### ISSUE TITLE
Fix window manager view rendering Material3 Compose Bottom Sheet over AccessibilityRenderExtension info.

### ISSUE THREAD

**Issue by geoff-powell** [cashapp/paparazzi#1634]
**Description**
When bumping LayoutLib dependency to 14.0.11+, Material3 bottom sheets render overtop the render extension metadata. This issue is to investigate a possible fix. Ignoring the test `modalBottomSheetMaterial3` in this [LayoutLib bump PR](https://github.com/cashapp/paparazzi/pull/1578) till this issue is resolved.
![Image](https://github.com/user-attachments/assets/c0a61189-cafb-4cb6-9163-87b6d813e9d3)

**Steps to Reproduce**
- Remove @Ignore in `modalBottomSheetMaterial3()` in compose-a11y test project test foile.
- Run `composeA11y` test in PaparazziGradlePluginTest.kt.

**Expected behavior**
Snapshot is unchanged.

**Additional information:**
- Paparazzi Version: 1.3.5 ([renovate/layoutlib](https://github.com/cashapp/paparazzi/pull/1633/commits/728a77a653da5ae9f33062b8d23b3b7455d7c5e7))
- OS: Mac OS 
- Compile SDK: 34
- Gradle Version: 8.7.1
- Android Gradle Plugin Version: 8.4.2

**Screenshots**
See above

**Comment by jrodbx** [comment]
@geoff-powell since this is a known regression, can we get this fix in for 1.3.5?

**Comment by geoff-powell** [comment]
> [@geoff-powell](https://github.com/geoff-powell) since this is a known regression, can we get this fix in for 1.3.5?

Yeah, let me take a look at this today

**Comment by geoff-powell** [comment]
WindowManagerImpl change is the root cause from 14.0.9 -> 14.0.11. https://www.diffchecker.com/fHBDkOTq/
