### ISSUE TITLE
Suggest using setLockableReadOnly in documentation

### ISSUE THREAD

**Issue by mr-thierry** [cashapp/paparazzi#1729]
We have seen great improvement to our git checkout speed if we set `lfs.setLockableReadOnly=false`.

See:

- https://github.com/git-lfs/git-lfs/issues/5897
- https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-track.adoc
- https://github.com/git-lfs/git-lfs/blob/main/docs/man/git-lfs-config.adoc

**Comment by wbrawner** [comment]
Better yet, should we just add it to the `bootstrap` script? E.g.

```bash
git config lfs.setLockableReadOnly false
```

**Comment by geoff-powell** [comment]
Thanks for the suggestion (kudos @joshfriend)!
