### ISSUE TITLE
android.content.res.Resources$NotFoundException when accessing app module resource from library module

### ISSUE THREAD

**Issue by ziem** [cashapp/paparazzi#1735]
**Description**
When you try to snapshot a composable that is using some resources from the app module, the "NotFoundException: Could not resolve resource value" exception is thrown.

This is very similar to the #1060 but doesn't involve a dynamic feature module. I'm not sure if the root cause is the same.

**Steps to Reproduce**
- checkout https://github.com/ziem/paparazzi/pull/1
- run `GreetingTest`

<details>
<summary>Full scracktrace</summary>

  >Could not resolve resource value: 0x7F09000E.
  >android.content.res.Resources$NotFoundException: Could not resolve resource value: 0x7F09000E.
  >	at app//android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1137)
  >	at app//android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1113)
  >	at app//android.content.res.Resources_Delegate.throwException(Resources_Delegate.java:1117)
  >	at app//android.content.res.Resources_Delegate.getString(Resources_Delegate.java:800)
  >	at app//android.content.res.Resources.getString(Resources.java:559)
  >	at app//androidx.compose.ui.res.StringResources_androidKt.stringResource(StringResources.android.kt:35)
  >	at app//com.example.app.MainActivityKt.Greeting(MainActivity.kt:36)
  >	at app//app.cash.paparazzi.sample.ComposableSingletons$HelloTestKt$lambda-1$1.invoke(HelloTest.kt:16)
  >	at app//app.cash.paparazzi.sample.ComposableSingletons$HelloTestKt$lambda-1$1.invoke(HelloTest.kt:16)
  >	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
  >	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
  >	at app//androidx.compose.ui.platform.ComposeView.Content(ComposeView.android.kt:441)
  >	at app//androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:259)
  >	at app//androidx.compose.ui.platform.AbstractComposeView$ensureCompositionCreated$1.invoke(ComposeView.android.kt:258)
  >	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
  >	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
  >	at app//androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
  >	at app//androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:216)
  >	at app//androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:132)
  >	at app//androidx.compose.ui.platform.AndroidCompositionLocals_androidKt$ProvideAndroidCompositionLocals$3.invoke(AndroidCompositionLocals.android.kt:131)
  >	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
  >	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
  >	at app//androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:380)
  >	at app//androidx.compose.ui.platform.AndroidCompositionLocals_androidKt.ProvideAndroidCompositionLocals(AndroidCompositionLocals.android.kt:121)
  >	at app//androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:155)
  >	at app//androidx.compose.ui.platform.WrappedComposition$setContent$1$1$3.invoke(Wrapper.android.kt:154)
  >	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
  >	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
  >	at app//androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:401)
  >	at app//androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:154)
  >	at app//androidx.compose.ui.platform.WrappedComposition$setContent$1$1.invoke(Wrapper.android.kt:133)
  >	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:109)
  >	at app//androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.jvm.kt:35)
  >	at app//androidx.compose.runtime.ActualJvm_jvmKt.invokeComposable(ActualJvm.jvm.kt:97)
  >	at app//androidx.compose.runtime.ComposerImpl.doCompose(Composer.kt:3595)
  >	at app//androidx.compose.runtime.ComposerImpl.composeContent$runtime_release(Composer.kt:3522)
  >	at app//androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:743)
  >	at app//androidx.compose.runtime.Recomposer.composeInitial$runtime_release(Recomposer.kt:1122)
  >	at app//androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:649)
  >	at app//androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:635)
  >	at app//androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:133)
  >	at app//androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:124)
  >	at app//androidx.compose.ui.platform.AndroidComposeView.setOnViewTreeOwnersAvailable(AndroidComposeView.android.kt:1626)
  >	at app//androidx.compose.ui.platform.WrappedComposition.setContent(Wrapper.android.kt:124)
  >	at app//androidx.compose.ui.platform.WrappedComposition.onStateChanged(Wrapper.android.kt:180)
  >	at app//androidx.lifecycle.LifecycleRegistry$ObserverWithState.dispatchEvent(LifecycleRegistry.jvm.kt:320)
  >	at app//androidx.lifecycle.LifecycleRegistry.addObserver(LifecycleRegistry.jvm.kt:198)
  >	at app//androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:131)
  >	at app//androidx.compose.ui.platform.WrappedComposition$setContent$1.invoke(Wrapper.android.kt:124)
  >	at app//androidx.compose.ui.platform.AndroidComposeView.onAttachedToWindow(AndroidComposeView.android.kt:1707)
  >	at app//android.view.View.dispatchAttachedToWindow(View.java:22860)
  >	at app//android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3492)
  >	at app//android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3499)
  >	at app//android.view.ViewGroup.addViewInner(ViewGroup.java:5299)
  >	at app//android.view.ViewGroup.addView(ViewGroup.java:5085)
  >	at app//android.view.ViewGroup.addView(ViewGroup.java:5025)
  >	at app//android.view.ViewGroup.addView(ViewGroup.java:4997)
  >	at app//app.cash.paparazzi.PaparazziSdk.takeSnapshots(PaparazziSdk.kt:279)
  >	at app//app.cash.paparazzi.PaparazziSdk.snapshot(PaparazziSdk.kt:176)
  >	at app//app.cash.paparazzi.PaparazziSdk.snapshot$default(PaparazziSdk.kt:174)
  >	at app//app.cash.paparazzi.PaparazziSdk.snapshot(PaparazziSdk.kt:171)
  >	at app//app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:100)
  >	at app//app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:97)
  >	at app//app.cash.paparazzi.sample.HelloTest.hello(HelloTest.kt:16)
  >	at java.base@21.0.3/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
  >	at java.base@21.0.3/java.lang.reflect.Method.invoke(Unknown Source)
  >	at app//org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
  >	at app//org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
  >	at app//org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
  >	at app//org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
  >	at app//app.cash.paparazzi.Paparazzi$apply$1.evaluate(Paparazzi.kt:76)
  >	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
  >	at app//org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
  >	at app//org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
  >	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
  >	at app//org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
  >	at app//org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
  >	at app//org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
  >	at app//org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
  >	at app//org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
  >	at app//org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
  >	at app//org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
  >	at app//org.junit.runners.ParentRunner.run(ParentRunner.java:413)
  >	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.runTestClass(JUnitTestClassExecutor.java:112)
  >	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:58)
  >	at org.gradle.api.internal.tasks.testing.junit.JUnitTestClassExecutor.execute(JUnitTestClassExecutor.java:40)
  >	at org.gradle.api.internal.tasks.testing.junit.AbstractJUnitTestClassProcessor.processTestClass(AbstractJUnitTestClassProcessor.java:54)
  >	at org.gradle.api.internal.tasks.testing.SuiteTestClassProcessor.processTestClass(SuiteTestClassProcessor.java:53)
  >	at java.base@21.0.3/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
  >	at java.base@21.0.3/java.lang.reflect.Method.invoke(Unknown Source)
  >	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:36)
  >	at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
  >	at org.gradle.internal.dispatch.ContextClassLoaderDispatch.dispatch(ContextClassLoaderDispatch.java:33)
  >	at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:92)
  >	at jdk.proxy2/jdk.proxy2.$Proxy6.processTestClass(Unknown Source)
  >	at org.gradle.api.internal.tasks.testing.worker.TestWorker$2.run(TestWorker.java:183)
  >	at org.gradle.api.internal.tasks.testing.worker.TestWorker.executeAndMaintainThreadName(TestWorker.java:132)
  >	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:103)
  >	at org.gradle.api.internal.tasks.testing.worker.TestWorker.execute(TestWorker.java:63)
  >	at org.gradle.process.internal.worker.child.ActionExecutionWorker.execute(ActionExecutionWorker.java:56)
  >	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:121)
  >	at org.gradle.process.internal.worker.child.SystemApplicationClassLoaderWorker.call(SystemApplicationClassLoaderWorker.java:71)
  >	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.run(GradleWorkerMain.java:69)
  >	at app//worker.org.gradle.process.internal.worker.GradleWorkerMain.main(GradleWorkerMain.java:74)
</details>

**Expected behavior**
It should not throw the NotFoundException.

**Additional information:**
- Paparazzi Version: 1.3.5
- OS: macOS
- Compile SDK: 34
- Gradle Version: 8.7, 8.11.1
- Android Gradle Plugin Version: 8.5.1, 8.7.3

**Screenshots**

**Comment by geoff-powell** [comment]
So looking at your repo, you have an andorid application module `app` that is a dependency on another android application module `sample`.

This is expected as the AndroidGradlePlugin doesn't provide us with the package named resources. 

When trying to view it in a preview, AS shows a similar error finding the resource.
![Image](https://github.com/user-attachments/assets/9e2da160-acbd-4358-b4d4-d0223b1ab485)


Closing this as it doesn't make sense to implement now. This might change when https://github.com/cashapp/paparazzi/issues/1060 is fixed.
