### ISSUE TITLE
Parameterized Paparazzi tests

### ISSUE THREAD

**Issue by Egorand** [cashapp/paparazzi#180]
It would be nice to have a way to run every test multiple times with different configurations, e.g. dark vs light mode, different accessibility settings, portrait vs landscape etc. This can theoretically be achieved with a custom test runner (similar to `Parameterized`), but this would make it hard to use any other runner with Paparazzi tests. Perhaps the `Paparazzi` test rule can accept a list of customizable configurations, each of which will affect `paparazzi.context`, and the rule will ensure that every test is ran with every configuration?

**Comment by JakeWharton** [comment]
What's wrong with using `Parameterized` or [Burst](https://github.com/square/burst/) today? It should work fine.

**Comment by Egorand** [comment]
I'd like to have a less boilerplate-y solution. I can write my own test runner and use it for all snapshot tests, but then none of them will be able to use any other test runners.

**Comment by JakeWharton** [comment]
I don't understand what you mean by boilerplate.

Why would we reinvent a mechanism that already exists and is the standard way of varying tests over input?

**Comment by Egorand** [comment]
I added this to the test I wrote:
```kotlin
companion object {
  @JvmStatic
  @Parameters(name = "Theme: {0}")
  fun inputs(): Collection<Array<Any>> {
    return listOf(
      arrayOf(Light),
      arrayOf(Dark),
    )
  }
}
```
I'd like to have this in every Paparazzi test class without copy pasta. Probably there's a good way to abstract this over Paparazzi which I'm missing.

**Comment by JakeWharton** [comment]
I'm not really seeing that as boilerplate since it's a mechanism by which I can also vary the test based on other parameters if required.

Would a factory to produce the cartesian product of input arrays be sufficient?
```kotlin
private inline fun <reified T> cartesianProduct(vararg lists: List<T>): List<Array<T>> {
  return lists.fold(listOf(emptyArray())) { partials, list ->
    partials.flatMap { partial -> list.map { element -> partial + element } }
  }
}
```
then you can do
```kotlin
@JvmStatic
@Parameters(name = "size={0}, sparse={1}")
fun parameters() = cartesianProduct(
  listOf(10, 100, 1_000, 10_000),
  listOf(true, false)
)
```
for example.

This means you can abstract your theme list out into a shared constant and then update your test to
```kotlin
@JvmStatic
@Parameters(name = "theme={0}")
fun parameters() = cartesianProduct(standardThemes)
```

**Comment by Egorand** [comment]
This helps somewhat, but I'm mostly concerned about having to add parameters to every class explicitly. Ideally I'd like to just add the Paparazzi test rule and have parameterized test runs out of the box.

**Comment by jrodbx** [comment]
This is a JUnit test configuration concern, not Paparazzi's.

https://github.com/cashapp/paparazzi/pull/190 enables support for Burst, which supports this behavior.
