### ISSUE TITLE
Enable code completion for test projects

### ISSUE THREAD

**Issue by saket** [cashapp/paparazzi#191]
Adding new test projects to `/paparazzi-gradle-plugin/src/test` is slightly painful right now because code completion doesn't work. Is this something that can be enabled?

**Comment by TWiStErRob** [comment]
I don't think that's possible, because build.gradle will only have completion if you synced that project. There's an implicit pluginClasspath hidden by the Gradle test kit, so IDEA has no chance of discovering where to get the dependencies from.
