### ISSUE TITLE
Sources jar for layoutlib is empty

### ISSUE THREAD

**Issue by madisp** [cashapp/paparazzi#214]
I've got a view inflation failure originating from an assert in layoutlib and it's very hard to track down as I can't easily place breakpoints into layoutlib due to missing sources.

It would be nice if the published sources jar wasn't empty:

```
$ unzip -lv /Users/madis/.gradle/caches/modules-2/files-2.1/app.cash.paparazzi/layoutlib-jdk11/4.0.0-alpha02-b169460/2d4f038e18d128a9de2786c4288d6034c7a0807d/layoutlib-jdk11-4.0.0-alpha02-b169460-sources.jar
 Length   Method    Size  Cmpr    Date    Time   CRC-32   Name
--------  ------  ------- ---- ---------- ----- --------  ----
       0  Defl:N        2   0% 10-02-2020 11:46 00000000  META-INF/
      25  Defl:N       27  -8% 10-02-2020 11:46 ee027fb2  META-INF/MANIFEST.MF
--------          -------  ---                            -------
      25               29 -16%                            2 files
```

**Comment by jrodbx** [comment]
Definitely!

At the moment, we use a [prebuilt version of layout-lib](https://android.googlesource.com/platform/prebuilts/studio/layoutlib/+log/refs/tags/studio-4.0.0), but it would be nice to figure out how to compile and push a source jar.

**Comment by liutikas** [comment]
https://issuetracker.google.com/issues/241795063 is the upstream request for publishing layout lib directly by Google

**Comment by TWiStErRob** [comment]
If you know the tag/hash, it's enough to just zip it up, isn't it? Until they actually complete the related ticket, even a handzipped version would help a ton.

**Comment by liutikas** [comment]
Layoutlib jar is built from multiple git repositories from branches that are not open to public, so sadly there is nothing to point to that has everything.

**Comment by jrodbx** [comment]
Closed by moving to Google's layoutlib in https://github.com/cashapp/paparazzi/pull/1228
