### ISSUE TITLE
Paparazzi doesn't render TextView ellipsis

### ISSUE THREAD

**Issue by Egorand** [cashapp/paparazzi#221]
Steps to repro:

1. Run `recordPaparazzi` over a `TextView` with `ellipsize = TruncateAt.END`.

Expected:

- The ellipsis is visible on the snapshot

Actual:

- The ellipsis is not rendered

**Comment by jrodbx** [comment]
As a first-pass sanity check (to be added to an FAQ soon!),

1) Does the Legacy Layout Inspector handle this correctly?
2) Does the new Layout Inspector handle this correctly?

My _guess_ is this is one of the features that will come with using the native layoutlib, would you be able to verify this?

**Comment by jrodbx** [comment]
Fixed in https://github.com/cashapp/paparazzi/pull/251

![Screen Shot 2021-09-10 at 2 26 44 PM](https://user-images.githubusercontent.com/1868149/132900463-3bbc4c44-503a-4d21-89c5-e9903609b12f.png)
