### ISSUE TITLE
Support dynamic-library modules

### ISSUE THREAD

**Issue by RainNapper** [cashapp/paparazzi#260]
`plugin: com.android.dynamic-feature`
Currently, you get a similar issue to trying to reference resources from an application module, presumably because the resources are encoded in some binary format that Paparazzi cannot read.

This results in `null` being returned when trying to inflate a view, and a Kotlin error that reads roughly like "null cannot be cast to non-null type V"

Likely overlap with issue https://github.com/cashapp/paparazzi/issues/107

**Comment by jrodbx** [comment]
Fixed in https://github.com/cashapp/paparazzi/pull/960
