### ISSUE TITLE
Add record boolean to Paparazzi constructor

### ISSUE THREAD

**Issue by ncipollo** [cashapp/paparazzi#292]
It would be awesome if the Paparazzi constructor accepted a boolean or enum which would set it up to either run tests in recording mode or validating mode (or reporting mode). In my project I have a little wrapping rule around Paparazzi with a record flag which does the following:
```kotlin
val verify = !record
System.setProperty("paparazzi.test.record", record.toString())
System.setProperty("paparazzi.test.verify", verify.toString())
```

This is nice because it lets you re-record a single test or an entire test class as opposed to all of the tests in a module.

**Comment by jrodbx** [comment]
Yea, we considered that, but ultimately decided that the supported way to configure modes is via the system properties to avoid test authors having to update test sources.

>  it lets you re-record a single test or an entire test class as opposed to all of the tests in a module

There *is* a way to do this is with gradle syntax on CLI, i.e., 

`./gradlew module:recordPaparazziDebug --tests=com.example.FooTest.testMethod`

We've also talked about providing an Intelli plugin that would supply ways to create a custom run configuration that would do this from the IDE.

Hope this helps!

**Comment by ncipollo** [comment]
Thanks for the reply @jrodbx! That does help, though it's a tiny bit more cumbersome than being able to record from the IDE. The rationale for not wanting people to have to update code to record makes sense though. 

As long as those system properties are relatively stable I think I can support my usecase with the wrapping test rule I made.
