### ISSUE TITLE
Please provide CONTRIBUTING.md or DEVELOPMENT.md with some warnings

### ISSUE THREAD

**Issue by TWiStErRob** [cashapp/paparazzi#299]
I tried to set up the project, use `gradlew publishToMavenLocal` to verify a change. After 30 minutes of downloading 
```
> Task :libs:layoutlib:cloneLayoutlib
Cloning prebuilt layoutlib: this make take a few minutes...
```
filled my disk to 0 bytes. The size of `build\prebuilts\studio` was 6GB. This was quite unexpected. Is there a way to skip this step and only publish jars, using the pre-built jar from mavenCentral?

I think https://github.com/cashapp/paparazzi/blob/master/libs/README.md might be outdated.
Maybe there's a way to not clone everything, but just checkout/download the exact hash's packs?

**Comment by TWiStErRob** [comment]
settings.gradle change worked:
```
//include ':libs:layoutlib'
//include ':libs:native-macosx'
//include ':libs:native-win'
//include ':libs:native-linux'
```
I guess I'm calling the wrong publishXXXToMavenLocal task.

**Comment by jrodbx** [comment]
https://github.com/cashapp/paparazzi/blob/master/libs/README.md

**Comment by TWiStErRob** [comment]
Yeah I saw that, but it says 2.4GB, and doesn't provide a workaround.

I think you got it the wrong way around, I just want to hack around in the Paparrazi sourcecode and not deal with layoutlib on my local build.

**Comment by TWiStErRob** [comment]
Hmm, publishToMavenLocal is the standard Gradle publication mechanism. I was `publications {}`, thanks for the pointer to vanniktech.

**Comment by jrodbx** [comment]
> I think you got it the wrong way around, I just want to hack around in the Paparrazi sourcecode and not deal with layoutlib on my local build.

I see.  I was going by the `:libs:layoutlib:cloneLayoutlib` snippet pasted above.

To test Paparazzi sources locally, a similar command
`./gradlew clean publishMavenPublicationToMavenLocal paparazzi-gradle-plugin:publishPluginMavenPublicationToMavenLocal`

will publish the jars
