### ISSUE TITLE
Writing RenderExtensions vs non-existent BufferedImage

### ISSUE THREAD

**Issue by TWiStErRob** [cashapp/paparazzi#306]
I'm in an android library module's Unit Test source set and I get an error on `java.awt.image.BufferedImage`.
![image](https://user-images.githubusercontent.com/2906988/140639583-3a09d3bf-9a2b-42ff-9362-1afc9aa006a0.png)

This somehow compiles and runs locally, but is red in IntelliJ IDEA and on CI.
```
> Task :component:widget:compileDebugUnitTestJavaWithJavac
/home/runner/work/net.twisterrob.sun/net.twisterrob.sun/component/widget/src/test/java/net/twisterrob/sun/test/screenshots/CropViewRenderExtension.java:3: error: package java.awt.image does not exist

import java.awt.image.BufferedImage;
                     ^
/home/runner/work/net.twisterrob.sun/net.twisterrob.sun/component/widget/src/test/java/net/twisterrob/sun/test/screenshots/CropViewRenderExtension.java:17: error: cannot find symbol
				@NonNull BufferedImage image) {
				         ^
  symbol:   class BufferedImage
  location: class net.twisterrob.sun.test.screenshots.CropViewRenderExtension
/home/runner/work/net.twisterrob.sun/net.twisterrob.sun/component/widget/src/test/java/net/twisterrob/sun/test/screenshots/CropViewRenderExtension.java:14: error: cannot find symbol
		public @NonNull BufferedImage render(
		                ^
  symbol:   class BufferedImage
  location: class net.twisterrob.sun.test.screenshots.CropViewRenderExtension
3 errors

> Task :component:widget:compileDebugUnitTestJavaWithJavac FAILED
```

**Comment by geoff-powell** [comment]
@TWiStErRob I changed the api for `RenderExtension` to manipulate the view hierarchy instead of the BufferedImage. I am curious if this use case of you have to manipulate the image after the view was rendered. Happy to add better support for this. RenderExtension is currently in its early stages.

**Comment by TWiStErRob** [comment]
Simple: most views are not full screen. If a view is not `match_parent`, there's wasted space in the image or unnecessary scaling.

I personally was setting up this for a home screen widget, which means I have to provide a container of size 1x1 cell (~100x80dp).
At DroidCon someone (from Facebook?) mentioned they use a similar extension to also cut just the targeted area.

**Comment by geoff-powell** [comment]
Got it that makes sense. Here is an initial attempt to providing this functionality. 
https://github.com/cashapp/paparazzi/compare/gpowell/sample-widget-render-extension?expand=1

**Comment by TWiStErRob** [comment]
Closing this as outdated, in Paparazzi 1.0 `RenderExtension` is a `(View) -> View`, so not an issue.
