### ISSUE TITLE
Faster :libs:layoutlib and :libs:native-* builds

### ISSUE THREAD

**Issue by TWiStErRob** [cashapp/paparazzi#314]
Have you considered using Gitiles's tgz feature?

Knowing `layoutLibPrebuiltSha` (e.g. current one `852189b`)
It's possible to look up the commit (for humans):
https://android.googlesource.com/platform/prebuilts/studio/layoutlib/+/852189b

and download a tgz file (for `cloneLayoutLib` task):
https://android.googlesource.com/platform/prebuilts/studio/layoutlib/+archive/852189b.tar.gz
which is only 200MB.
The tree tgz link and the commit tgz link will yield the same archive.

Sidenote: In case you want to use tags and not sha, this will resolve to the tag to commit history:
This contains the https://android.googlesource.com/platform/prebuilts/studio/layoutlib/+log/refs/tags/studio-4.0.0?format=JSON

**Comment by jrodbx** [comment]
TIL, I'll keep that in mind if I ever deal with AOSP prebuilts in the future.  However, I think next steps on optimizing this would be to built from source.
