### ISSUE TITLE
Lift reports OSS vulnerabilities from Paparazzi transitive deps

### ISSUE THREAD

**Issue by TWiStErRob** [cashapp/paparazzi#363]
https://lift.sonatype.com/results/github.com/TWiStErRob/net.twisterrob.sun/01FTFZF4H491509KXTNG4MT4Q7
(Note: for me the UI is broken, have to click "Show Details" and then "Components", viewing Components outside doesn't expand.)

![image](https://user-images.githubusercontent.com/2906988/188401149-7dcd856e-8fea-44e8-86cf-90042ae1bc13.png)

![image](https://user-images.githubusercontent.com/2906988/188401260-e892c27a-ddc3-4d6c-9914-c1dafb77ee77.png)

Search `HERE` in below block.
```
+--- app.cash.paparazzi:paparazzi:0.9.0
|    +--- app.cash.paparazzi:layoutlib-native-jdk11:2020.3.1-852189b
|    +--- com.android.tools:common:27.1.2 -> 27.2.2
|    |    +--- com.android.tools:annotations:27.2.2
|    |    \--- com.google.guava:guava:28.1-jre -> 31.0.1-jre
|    |         +--- com.google.guava:failureaccess:1.0.1
|    |         +--- com.google.guava:listenablefuture:9999.0-empty-to-avoid-conflict-with-guava
|    |         +--- com.google.code.findbugs:jsr305:3.0.2
|    |         +--- org.checkerframework:checker-qual:3.12.0
|    |         +--- com.google.errorprone:error_prone_annotations:2.7.1
|    |         \--- com.google.j2objc:j2objc-annotations:1.3
|    +--- com.android.tools.layoutlib:layoutlib-api:27.2.2
|    |    +--- com.android.tools:common:27.2.2 (*)
|    |    +--- net.sf.kxml:kxml2:2.3.0
|    |    +--- com.android.tools:annotations:27.2.2
|    |    \--- org.jetbrains:annotations:13.0
|    +--- com.android.tools:sdk-common:26.6.4
|    |    +--- com.android.tools:sdklib:26.6.4
|    |    |    +--- com.android.tools.layoutlib:layoutlib-api:26.6.4 -> 27.2.2 (*)
|    |    |    +--- com.android.tools:dvlib:26.6.4
|    |    |    |    \--- com.android.tools:common:26.6.4 -> 27.2.2 (*)
|    |    |    +--- com.android.tools:repository:26.6.4
|    |    |    |    +--- com.android.tools:common:26.6.4 -> 27.2.2 (*)
|    |    |    |    +--- com.sun.activation:javax.activation:1.2.0
|    |    |    |    +--- org.apache.commons:commons-compress:1.12 <------ HERE
|    |    |    |    +--- org.glassfish.jaxb:jaxb-runtime:2.3.1
|    |    |    |    |    +--- javax.xml.bind:jaxb-api:2.3.1
|    |    |    |    |    |    \--- javax.activation:javax.activation-api:1.2.0
|    |    |    |    |    +--- org.glassfish.jaxb:txw2:2.3.1
|    |    |    |    |    +--- com.sun.istack:istack-commons-runtime:3.0.7
|    |    |    |    |    +--- org.jvnet.staxex:stax-ex:1.8
|    |    |    |    |    +--- com.sun.xml.fastinfoset:FastInfoset:1.2.15
|    |    |    |    |    \--- javax.activation:javax.activation-api:1.2.0
|    |    |    |    +--- com.google.jimfs:jimfs:1.1
|    |    |    |    |    \--- com.google.guava:guava:18.0 -> 31.0.1-jre (*)
|    |    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.71 -> 1.5.31
|    |    |    |         +--- org.jetbrains.kotlin:kotlin-stdlib:1.5.31
|    |    |    |         |    +--- org.jetbrains:annotations:13.0
|    |    |    |         |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31
|    |    |    |         \--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.31
|    |    |    |              \--- org.jetbrains.kotlin:kotlin-stdlib:1.5.31 (*)
|    |    |    +--- com.google.code.gson:gson:2.8.5
|    |    |    +--- org.apache.commons:commons-compress:1.12 <------ HERE
|    |    |    +--- org.apache.httpcomponents:httpmime:4.5.6
|    |    |    |    \--- org.apache.httpcomponents:httpclient:4.5.6 <------ HERE
|    |    |    |         +--- org.apache.httpcomponents:httpcore:4.4.10
|    |    |    |         +--- commons-logging:commons-logging:1.2
|    |    |    |         \--- commons-codec:commons-codec:1.10
|    |    |    \--- org.apache.httpcomponents:httpcore:4.4.10
|    |    +--- com.android.tools.build:builder-test-api:3.6.4
|    |    |    \--- com.android.tools.ddms:ddmlib:26.6.4
|    |    |         +--- com.android.tools:common:26.6.4 -> 27.2.2 (*)
|    |    |         \--- net.sf.kxml:kxml2:2.3.0
|    |    +--- com.android.tools.build:builder-model:3.6.4
|    |    |    \--- com.android.tools:annotations:26.6.4 -> 27.2.2
|    |    +--- com.android.tools.ddms:ddmlib:26.6.4 (*)
|    |    +--- com.android.tools.analytics-library:shared:26.6.4
|    |    |    +--- com.android.tools.analytics-library:protos:26.6.4
|    |    |    |    \--- com.google.protobuf:protobuf-java:3.4.0
|    |    |    +--- com.android.tools:annotations:26.6.4 -> 27.2.2
|    |    |    +--- com.android.tools:common:26.6.4 -> 27.2.2 (*)
|    |    |    +--- com.google.guava:guava:27.1-jre -> 31.0.1-jre (*)
|    |    |    +--- com.google.code.gson:gson:2.8.5
|    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.71 -> 1.5.31 (*)
|    |    +--- org.bouncycastle:bcpkix-jdk15on:1.56
|    |    |    \--- org.bouncycastle:bcprov-jdk15on:1.56 <------ HERE
|    |    +--- org.bouncycastle:bcprov-jdk15on:1.56 <------ HERE
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.3.71 -> 1.5.31 (*)
|    |    +--- org.jetbrains.kotlin:kotlin-reflect:1.3.71 -> 1.5.31
|    |    |    \--- org.jetbrains.kotlin:kotlin-stdlib:1.5.31 (*)
|    |    +--- com.google.protobuf:protobuf-java:3.4.0
|    |    +--- javax.inject:javax.inject:1
|    |    +--- org.jetbrains.trove4j:trove4j:20160824
|    |    \--- com.android.tools.build:aapt2-proto:0.4.0
|    |         \--- com.google.protobuf:protobuf-java:3.4.0
|    +--- kxml2:kxml2:2.3.0
|    |    \--- net.sf.kxml:kxml2:2.3.0
|    +--- junit:junit:4.13.2
|    |    \--- org.hamcrest:hamcrest-core:1.3
|    +--- androidx.annotation:annotation:1.3.0
|    +--- com.google.guava:guava:31.0.1-jre (*)
|    +--- org.jetbrains.kotlinx:kotlinx-coroutines-core:1.5.2
|    |    \--- org.jetbrains.kotlinx:kotlinx-coroutines-core-jvm:1.5.2
|    |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.30 -> 1.5.31 (*)
|    |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.5.30 -> 1.5.31
|    +--- com.squareup.okio:okio:3.0.0
|    |    \--- com.squareup.okio:okio-jvm:3.0.0
|    |         +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31 (*)
|    |         \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31
|    +--- org.jetbrains.kotlin:kotlin-bom:1.5.31
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31 (c)
|    |    +--- org.jetbrains.kotlin:kotlin-reflect:1.5.31 (c)
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib:1.5.31 (c)
|    |    +--- org.jetbrains.kotlin:kotlin-stdlib-jdk7:1.5.31 (c)
|    |    \--- org.jetbrains.kotlin:kotlin-stdlib-common:1.5.31 (c)
|    \--- org.jetbrains.kotlin:kotlin-stdlib-jdk8:1.5.31 (*)
```

**Comment by fcduarte** [comment]
We might have a hard time to solve this one since latest version at time of writing -- https://mvnrepository.com/artifact/com.android.tools/sdk-common/30.4.0-alpha08 -- still have two vulnerabilities.

**Comment by TWiStErRob** [comment]
That's less than 7 :)

**Comment by TWiStErRob** [comment]
Note that all of those vulnerabilities are patched in the corresponding latest libs. So maybe exposing newer versions of those transitive deps from paparazzi is a solution?

**Comment by jrodbx** [comment]
> Note that all of those vulnerabilities are patched in the corresponding latest libs. So maybe exposing newer versions of those transitive deps from paparazzi is a solution?

@TWiStErRob curious: how were you able to confirm this?  I see alpha09 still has vulnerabilities and alpha10 doesn't have an entry on mvnrepository.  Did you push a test PR or something?

**Comment by TWiStErRob** [comment]
@jrodbx no, I think I was talking about the transitive deps ("corresponding"), so:
[30.4.0-alpha08](https://mvnrepository.com/artifact/com.android.tools/sdk-common/30.4.0-alpha08) has a table showing
 * gson 2.8.6 (1 vul) -> 2.9.1 (0 vul), and if you open [gson](https://mvnrepository.com/artifact/com.google.code.gson/gson) you can see it was fixed in 2.8.9, which is used by [30.4.0-alpha09](https://mvnrepository.com/artifact/com.android.tools/sdk-common/30.4.0-alpha09)
 * xerces 2.12.0 (2 vul) -> 2.12.2 (0 vul), again [xercesImpl](https://mvnrepository.com/artifact/xerces/xercesImpl) shows that 2.12.1 fixed one, and 2.12.2 fixed another.

Sadly [alpha09](https://mvnrepository.com/artifact/com.android.tools/sdk-common/30.4.0-alpha09) is still using a bad xerces version, and [alpha10](https://maven.google.com/web/index.html?q=sdk-comm#com.android.tools:sdk-common:30.4.0-alpha10) too (click on [pom](https://dl.google.com/android/maven2/com/android/tools/sdk-common/30.4.0-alpha10/sdk-common-30.4.0-alpha10.pom) and see last dependency in XML). If you have a channel to tell them to bump those two patches for xerces, at least the next release would fix it.

**Comment by TWiStErRob** [comment]
Based on the above, my idea would be
```patch
api deps.tools.common
+// gson and xercesImpl is included because deps.tools.common is using vulnerable transitive dependencies, see https://github.com/cashapp/paparazzi/issues/363
+api deps.transitive.gson // depending on which version is used
+api deps.transitive.xercesImpl
```

**Comment by anhanh11001** [comment]
Hi @jrodbx,

My team is considering adopting this library, and I wonder the impact of this issue:
- Does this still exist in 1.1.0?
- How would this affect the client application which use the library?
- When will this be patched/fixed?

Thanks for the work in the lib btw, this one is great!

**Comment by TWiStErRob** [comment]
@anhanh11001 I wouldn't be too worried about this, because if you use AGP, `com.android.tools.build:gradle` also depends on `sdk-common` and has the same vulnerabilities: https://mvnrepository.com/artifact/com.android.tools.build/gradle/7.3.1

Sorry, @fcduarte I forgot to file it yet, do you have an idea which component?

**Comment by JakeWharton** [comment]
Help > Submit Feedback in AS. Does all you need.

**Comment by TWiStErRob** [comment]
Nice, I didn't know about that, and also forgot the fact that mere humans can't select specific components in Google Issuetracker. Anyway, opened https://issuetracker.google.com/issues/262333727.

**Comment by jrodbx** [comment]
@TWiStErRob can this be closed now that we're on a later version of sdkcommon?

**Comment by TWiStErRob** [comment]
Not much has changed, see the upstream issue, even in AGP 8 versions they're not updated.

Here's my Paparazzi 1.2.0 upgrade branch report:

![Screenshot_20230126-092437](https://user-images.githubusercontent.com/2906988/214801062-d9f3a004-e2e8-47ff-82fb-c1c33913dd6d.png)

In [mvnrepository](https://mvnrepository.com/artifact/app.cash.paparazzi/paparazzi/1.2.0) the vulnerabilities are not transitively reported :( so we have to click into each to see.

That said, I guess we can close this if you're not going to explicitly bump those transitive versions e.g. by adding a [constraint](https://docs.gradle.org/current/userguide/dependency_constraints.html#sec:adding-constraints-transitive-deps).

**Comment by jrodbx** [comment]
Looks like sdk-common 31.3.0 will finally resolve this.

**Comment by jrodbx** [comment]
Fixed in https://github.com/cashapp/paparazzi/pull/1314/files#diff-697f70cdd88ba88fe77eebda60c7e143f6ad1286bca75017421e93ad84fb87df
