### ISSUE TITLE
Snapshot without a device frame

### ISSUE THREAD

**Issue by swankjesse** [cashapp/paparazzi#37]
Perhaps something like this:

```
    paparazzi.snapshot(avatar, "avatar", deviceFrame = DeviceFrame.NONE)
```

**Comment by nikwotton** [comment]
+1

**Comment by TWiStErRob** [comment]
Is this a duplicate of https://github.com/cashapp/paparazzi/issues/313?

**Comment by TWiStErRob** [comment]
Isn't testing a widget (`View` with specific w/h) the same as testing a composable `Button`?
