### ISSUE TITLE
Unable to build the library - No compatible plugin found in project xxx for publishing

### ISSUE THREAD

**Issue by eboudrant** [cashapp/paparazzi#381]
I'm unable to build the library, it seems the `org.ajoberstar.grgit` plugin is causing this issues with the publishing plugin: 

```
> Configure project :libs:native-win
No compatible plugin found in project native-win for publishing
```

While I can comment the publishing code is there a better way to fix it?

Sorry if this was already asked or documented, I could not find anything.

**Comment by jrodbx** [comment]
Can you elaborate on `unable to build the library`?  I see those same warnings for the :libs modules, but the build task for the other modules continue successfully.

**Comment by eboudrant** [comment]
Don't works (build is success but nothing happen): https://scans.gradle.com/s/dj3s5atd5ytdw
Passing after workaround https://scans.gradle.com/s/saqedss2bsltg

The new workaround I found is to add `apply plugin: 'org.jetbrains.kotlin.jvm'
` in the `libs` gradle files, ex:

<img width="597" alt="image" src="https://user-images.githubusercontent.com/773377/157754696-1411f76d-e98d-458f-ac85-167ffc825d82.png">

**Comment by jrodbx** [comment]
Ah I read `build the library` as `built the binary` as if you were looking to deploy for local development.

The build scan shows `sample:testDebug` completes successfully, so are you saying you don't see the html page as mentioned here: https://github.com/cashapp/paparazzi#tasks?

**Comment by eboudrant** [comment]
Oh, really sorry, I got confused by the warning and the fact that the Gradle build is blazing fast when all is up-to-date. I'm closing the issue.
