### ISSUE TITLE
Feature request: Snapshot of single Composable

### ISSUE THREAD

**Issue by andersu** [cashapp/paparazzi#383]
In the current snapshot testing library we are using, I can take a snapshot of a single component/composable:
![com action consumerapp components buttons PrimaryButtonScreenshotTest_testContent](https://user-images.githubusercontent.com/2194905/157846510-ac64d37f-799f-4fb3-823c-d8d14b7064ae.png)

Is that already possible with Paparazzi?

Or is it always a full screen like this?
![com action consumerapp buttons_PrimaryButtonPaparazziTest_testPrimaryButton](https://user-images.githubusercontent.com/2194905/157846613-e0602abb-7646-46b3-91f8-c6184a287e1e.png)

**Comment by hrach** [comment]
This workaround seems to work:
```kotlin
    val paparazzi = Paparazzi(
        deviceConfig = DeviceConfig.NEXUS_5.copy(softButtons = false, screenHeight = 1),
        renderingMode = SessionParams.RenderingMode.V_SCROLL,
    )
```
