### ISSUE TITLE
`"No source sets available"` if project doesn't set `packageName` in `AndroidManifest` (or doesn't have AndroidManifest.xml at all)

### ISSUE THREAD

**Issue by mateuszkwiecinski** [cashapp/paparazzi#387]
According to https://issuetracker.google.com/issues/172361895, setting `packageName` within `AndroidManifest.xml` file is not the recommended option. 

When applying Paparazzi plugin to a project that has already migrated to `namespace` any Paparazzi's task invocation ends with
```
Could not determine the dependencies of task ':ui:two-factor:android:recordPaparazziDebug'.
> Could not create task ':ui:two-factor:android:testDebugUnitTest'.
   > Could not create task ':ui:two-factor:android:preparePaparazziDebugResources'.
      > No source sets available
```
thrown from here: https://github.com/cashapp/paparazzi/blob/10e3e4dab82c08a74d3d3a413b51672791a90553/paparazzi-gradle-plugin/src/main/java/app/cash/paparazzi/gradle/PaparazziPlugin.kt#L220

Before throwing the exception, it would probably make sense to read `namespace` property  (or maybe the `testNamespace`?, I'm not sure what is it for 😬) 

I'd also suggest not to throw any exception at configuration phase at all. If it wasn't thrown that early, consumers could patch the config by manually configuring the required property. Current setup requires monkey patching by overriding plugin sources in `buildSrc`.
I verified locally using `android.namespace` fixes the issue in my setup, and I was able to record screenshots which 

version used `1.0.0-SNAPSHOT`

**Comment by jrodbx** [comment]
Thanks for the issue!  Also, TIL about `namespace`.
