### ISSUE TITLE
Is it possible to override Locale in paparazzi tests? 

### ISSUE THREAD

**Issue by saurabhkpatel** [cashapp/paparazzi#405]
**Context:** A use case in mind to run the UI screen tests and see how they look in the different locale copies.

**Background:**  Assuming that there is a different team that does the translations for your application and we want to make sure that the UI experience is good in different locales by comparing the screenshots or seeing them. I am looking for a way where I can override the locale and run the same tests so string resources will be picked up accordingly.

A few things I found so far:
- get the context from the paparazzi class and override the locale in it, I tried this but it seems layout lib doesn't honor the change. 

Any thoughts would be appreciated.

**Comment by saurabhkpatel** [comment]
@JackHurst0 : how `DeviceConfig` would work here? I think we need the override the locale under context which layoutlib uses, don't you think so?

**Comment by JackHurst0** [comment]
@saurabhkpatel Yes it looks like you are probably right. Optimistic thinking from me. Hopefully the maintainers of this library can at some point add in support to localisation, as this would make it incredibly useful for users working on localisation projects.

**Comment by dniHze** [comment]
I introduced a small change and added tests that allow locale and RTL override over `DeviceConfig` settings in #475. This works pretty well, but I'm not sure about the API. It looks like `DeviceConfig` is becoming too large and contains settings that have nothing to do with the actual "device".

**Comment by jannisveerkamp** [comment]
Maybe it would be possible to use a `ContextWrapper` somehow? E.g.:

```
class LocaleContextWrapper(base: Context, locale: Locale) : ContextWrapper(base) {

    private val resourceContext: Context = base.createConfigurationContext(
        base.resources.configuration.apply {
            setLocales(LocaleList(locale))
            Locale.setDefault(locale)
        }
    )

    override fun getResources(): Resources = resourceContext.resources
}
```

At least that would be an "natural" Android way.

Not sure if that works with the internals of paparazzi though 🤷‍♀️
