### ISSUE TITLE
Add helpful error message when missing platform

### ISSUE THREAD

**Issue by tir38** [cashapp/paparazzi#419]
I see that you already don't swallow FileNotFound exception when platform version is missing #224. It might be overkill, but maybe helpful to some to catch and rethrow with an additional error message to install requested version:

`Missing platform version 30. Install with $ sdkmanager --install "platforms;android-30"`

**Comment by kotya341** [comment]
do you know what mind cause this issue, when tools are installed 
I anyways getting this issue
`Install with sdkmanager --install "platforms;android-32"`
this is what installed 

```
❯ sdkmanager --list_installed |grep 32
  build-tools;32.0.0                                       | 32.0.0     | Android SDK Build-Tools 32                      | build-tools/32.0.0
  platforms;android-32                                     | 1          | Android SDK Platform 32                         | platforms/android-32
````

**Comment by tir38** [comment]
You could always try to update this line https://github.com/cashapp/paparazzi/pull/438/files#diff-f6f3c852cfa0f83f714de96946d6295ed17817f7e92040602147b4ecc58672eaR36

to print out `platformDirPath` to double check that paparazzi is using the same project directory as `sdkmanager`. I know it's possible to install SDK stuff to various directories

**Comment by kotya341** [comment]
> You could always try to update this line https://github.com/cashapp/paparazzi/pull/438/files#diff-f6f3c852cfa0f83f714de96946d6295ed17817f7e92040602147b4ecc58672eaR36
> 
> to print out `platformDirPath` to double check that paparazzi is using the same project directory as `sdkmanager`. I know it's possible to install SDK stuff to various directories

Thanks a lot for help, you was right 
A reason was as you suggesting incorrect path, but for my env variable for `ANDROID_SDK_ROOT`

**Comment by DusilB** [comment]
Having trouble with this as well. I can't use `sdkmanager` command though so may also be something wrong in my path. 
I can confirm I have the version of build tools I'm looking for though...

`Missing platform version 31. Install with sdkmanager --install "platforms;android-31"` 
<img width="732" alt="Screen Shot 2022-09-01 at 1 30 27 PM" src="https://user-images.githubusercontent.com/31486894/187976603-34f183c8-5f39-407a-a632-971e3baf730f.png">
