### ISSUE TITLE
NIGHT mode renders Compose as NOT_NIGHT

### ISSUE THREAD

**Issue by carl-lightricks** [cashapp/paparazzi#440]
Setting up a DeviceConfig with NightMode.NIGHT, renders identical to NightMode.NOT_NIGHT. ie it does not make a difference and my Composable cannot be rendered in nightmode.

```
@get:Rule
    val paparazzi = Paparazzi(
        deviceConfig = DeviceConfig.NEXUS_5.copy(softButtons = false, screenHeight = 1, nightMode = NightMode.NIGHT),
        renderingMode = SessionParams.RenderingMode.V_SCROLL,
    )


    @Test
    fun largeLozengeButton() {
        paparazzi.snapshot {
            LargeLozengeButton(text = "New Project", {})
        }
    }
```

I am using this implements:
`app.cash.paparazzi:paparazzi-gradle-plugin:1.0.0-SNAPSHOT`

**Comment by dniHze** [comment]
It looks like the frame of the system bars is affected by this setting, but `Configuration.uiMode` flags don't have `Configuration.UI_MODE_NIGHT_YES` in `Configuration.UI_MODE_NIGHT_MASK`. I will take a look into it to find a way to contribute a fix for this.

**Comment by dniHze** [comment]
Just created a workaround in #473. This theoretically should add support for night theming.
This is what I got locally after applying the fix.
| `NightMode.NOTNIGHT` | `NightMode.NIGHT` | 
| - | - |
| ![image](https://user-images.githubusercontent.com/6156111/175697697-745f7939-9aab-42bd-bd46-f33042d1a3d9.png) | ![image](https://user-images.githubusercontent.com/6156111/175697708-c3f93788-dc75-49c2-bb6a-b3e2ea1d91d2.png) | 

But I also want to test how it affects views: `DayNight` themes and `night` resource qualifier before making it ready for review.
