### ISSUE TITLE
[BUG] Compose support NoSuchMethodError

### ISSUE THREAD

**Issue by timrijckaert** [cashapp/paparazzi#449]
**Description**
Hello, 

I saw the announced that the library supports Compose and wanted to try it out.  
Since there is no documentation on how to setup Compose for now I took a best guess.  

Inside my personal project I could not get it to work.   
It would simply not generate any screenshot, even though the build does not fail.  
I decided to try create a Compose screenshot test from the :sample module in this repository.  

I created following test

```kotlin
package app.cash.paparazzi.sample

import androidx.compose.material.Text
import app.cash.paparazzi.Paparazzi
import org.junit.Rule
import org.junit.Test

class ComposeTest {

  @get:Rule
  val paparazzi = Paparazzi()

  @Test
  fun simpleComposable() {
    paparazzi.snapshot {
      Text("Hello world")
    }
  }
}
```

Upon running I get

```
app.cash.paparazzi.sample.ComposeTest > simpleComposable FAILED
    java.lang.NoSuchMethodError: 'void app.cash.paparazzi.Paparazzi.snapshot$default(app.cash.paparazzi.Paparazzi, java.lang.String, kotlin.jvm.functions.Function0, int, java.lang.Object)'
        at app.cash.paparazzi.sample.ComposeTest.simpleComposable(ComposeTest.kt:15)
```

What am I missing?

https://scans.gradle.com/s/xyqk34obtaxkc

**Additional information:**
- Paparazzi Version: 1.0.0
- OS: Mac AS Chipmunk 2021.2.1
- Compile SDK:  31 (:sample)
- Gradle Version: 7.4.2 (:sample)
- Android Gradle Plugin Version:  7.1.2 (:sample)

**Comment by JakeWharton** [comment]
Do you have `buildFeatures { compose = true }` in your build file? Seems like the Compose compiler is not running.

**Comment by timrijckaert** [comment]
Aha! Indeed I forgot to add that one!
Nice catch.

---

I dpn't know if I should open a ticket for this one, but I see there is some kind of a dependency on the `'org.jetbrains.kotlin.android'` plugin.  

I was looking for differences why it works in the demo project but not in my personal project.  

If you do not have the `'org.jetbrains.kotlin.android'` plugin applied the build does not fail, but simply does not generate any screenshot.

**Comment by JakeWharton** [comment]
Don't know off hand. File a new issue, ideally with a self-contained, minimal reproducing project.
