### ISSUE TITLE
No render on `Icon`

### ISSUE THREAD

**Issue by charbgr** [cashapp/paparazzi#454]
**Description**
I think that `Icon` does not being render at all at screenshots.

**Steps to Reproduce**
```
Column(verticalArrangement = Arrangement.spacedBy(16.dp)) {
    val sizeModifier = Modifier.size(16.dp)
    Icon(
        painter = painterResource(id = R.drawable.vd_info),
        contentDescription = null,
        modifier = sizeModifier,
    )
    Icon(
        painter = painterResource(id = R.drawable.vd_info),
        contentDescription = null,
        modifier = sizeModifier,
        tint = Color.Magenta,
    )
}
```

**Expected behavior**
To be rendered in screenshot.

**Additional information:**
- Paparazzi Version: 1.0.0 - 1.1.0-SNAPSHOT
- OS: macOS
- Compile SDK: 31
- Gradle Version: 7.4.2
- Android Gradle Plugin Version: 7.2.0

**Screenshots**
screen is empty :P

**Comment by jrodbx** [comment]
@charbgr According to this repro, Icon does appear to be rendering: https://github.com/cashapp/paparazzi/commit/1b99d8ca67e866c917821e3d15f83a3e43eaca1e#diff-eadd75cdb5ef5db0c475ad337aba758163c0e57f752b11bc86cf9a3ae56b8403

Closing as non-issue.  Let us know if you have any further insights into why this wasn't working for you.
