### ISSUE TITLE
Gradle errors

### ISSUE THREAD

**Issue by pvegh** [cashapp/paparazzi#464]
I see following error:

A problem occurred configuring project ':mymodule'.
> Could not determine the dependencies of null.
   > Could not resolve all task dependencies for configuration ':mymodule:classpath'.
      > Could not find com.android.tools.build:gradle:7.1.2.
        Searched in the following locations:
          - https://plugins.gradle.org/m2/com/android/tools/build/gradle/7.1.2/gradle-7.1.2.pom
        If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
        Required by:
            project :mymodule > app.cash.paparazzi:app.cash.paparazzi.gradle.plugin:1.0.0 > app.cash.paparazzi:paparazzi-gradle-plugin:1.0.0
      > Could not find com.android.tools:sdk-common:26.6.4.
        Searched in the following locations:
          - https://plugins.gradle.org/m2/com/android/tools/sdk-common/26.6.4/sdk-common-26.6.4.pom
        If the artifact you are trying to retrieve can be found in the repository but without metadata in 'Maven POM' format, you need to adjust the 'metadataSources { ... }' of the repository declaration.
        Required by:
            project :mymodule > app.cash.paparazzi:app.cash.paparazzi.gradle.plugin:1.0.0 > app.cash.paparazzi:paparazzi-gradle-plugin:1.0.0

**Steps to Reproduce**
1. Add the line to the module's build.gradle.kts:
id("app.cash.paparazzi") version "1.0.0"
2. sync in AS or ./gradlew assemble

**Expected behavior**
Successful sync/build

**Additional information:**
- Paparazzi Version:
- OS: MacOS 
- Compile SDK:
- Gradle Version: 7.5.rc1
- Android Gradle Plugin Version: 7.4.0-alpha05

**Comment by costular** [comment]
Hi @pvegh!

Are you adding the plugin in an application module? Keep in mind that Paparazzi only works with Android library modules

**Comment by pvegh** [comment]
plugins {
    id("com.android.library")
    kotlin("android")
    id("app.cash.paparazzi") version "1.0.0"
}

**Comment by AdamMc331** [comment]
I'm having the exact same issue. Any resolution, @pvegh ?

**Comment by costular** [comment]
Hey @pvegh @AdamMc331 

Try to add this block at the top of your Paparazzi module's `build.gradle`

```
buildscript {
    repositories {
        google()
    }
}
```

That should work so far, at least it did for me 😊

**Comment by AdamMc331** [comment]
@costular Thanks for the speedy response! This does seem to work, though I'm intrigued because my root `build.gradle` file was applying that repository to all subprojects, so I'd have expected it to just work with the existing configuration. Any idea why it didn't?

**Comment by msfjarvis** [comment]
> @costular Thanks for the speedy response! This does seem to work, though I'm intrigued because my root `build.gradle` file was applying that repository to all subprojects, so I'd have expected it to just work with the existing configuration. Any idea why it didn't?

I think the reason is that Paparazzi resolves its runtime dependencies from the plugin classpath which needs to either be configured from `settings.gradle.kts` using `pluginManagement.repositories` or from `build.gradle.kts` using `buildscript.repositories`. Using `(all|sub)projects.repositories` doesn't affect the plugin classpath.

**Comment by jrodbx** [comment]
Closing as resolved.  OP was confusing buildscript dependencies with subproject dependencies.
