### ISSUE TITLE
Out of memory exception with a lot of screenshots (compose)

### ISSUE THREAD

**Issue by badoualy** [cashapp/paparazzi#468]
**Description**
I have a test that generates a lot of screenshots (over a 1 000). (One component with a lot of display state possible, tested on 2 devices config, + light/dark mode, the total count is quickly reaching 1 000).

The first ~ 950 or so screenshots are going well, then I get the OOM exception on each one of them.

I'm using the following compose integration with showkase:
https://gist.github.com/alexvanyo/c4d2b6530f860f3c89a33324d4152ae8

In the mean time my solution was to create a shell script to run the test by batch of ~600 tests each, killing the jvm each time between runs.

**Additional information:**
- Paparazzi Version: 1.0.0
- OS: Windows

**Comment by fcduarte** [comment]
@badoualy that's an interesting case .. Do you happen to have a CI machine that runs in a different environment (Linux or MacOS)? This would help to pinpoint if this is an issue contained on Windows. Thanks!

**Comment by fcduarte** [comment]
@badoualy also it'd be great if you could post the stack trace so we can try to figure out where the OOM is coming from, thanks!

**Comment by jrodbx** [comment]
OOMs are extremely hard to repro or triage without some repro, however, if I had to guess, there are two likely causes for this:

1) Compose runtime has some known memory leaks.  This is out of our hands, although we have tried to remedy them somewhat here: https://github.com/cashapp/paparazzi/pull/430.
2) Your test jvm process needs more heap memory.  If you're using Gradle, the canonical way to bump that is in your gradle.properties, e.g.,: `org.gradle.jvmargs=-Xmx8192M`

**Comment by Jan-Ove** [comment]
We also had issues with OutOfMemoryErrors, and increasing the memory via the gradle.properties didn't solve it. I've discovered that it is possible to add jvmArgs via the testOptions block in the Gradle file and that solved our problem.
```kotlin
android {
    testOptions {
        unitTests {
            all {
                it.allJvmArgs = it.allJvmArgs + listOf("-Xmx4192M")
            }
        }
    }
}
```

**Comment by castorflex** [comment]
Note for future people: `jvmArgs = listOf("-Xmx4192M")` should be used instead of `allJvmArgs`, which can cause caching issues. See https://github.com/gradle/gradle/issues/25874
