### ISSUE TITLE
Use maxPercentDifference in record

### ISSUE THREAD

**Issue by yschimke** [cashapp/paparazzi#507]
**Description**

Configuration to respect maxPercentDifference during recordPaparazziDebug.
Given differences by JVM platform, often record phase generates a lot of diffs with meaningless diffs.  IT would be good to be able to configure to avoid updating snapshots, as it results in a commit war.

**Steps to Reproduce**

Checkout https://github.com/google/horologist

```
./gradlew recordPaparazziDebug
```

Diff the files

**Expected behavior**

No diffs, since verifyPaparazziDebug is passing.

**Additional information:**
- Paparazzi Version: 1.0

**Comment by jrodbx** [comment]
> Given differences by JVM platform

Fair to assume that all developers and CI builds should be aligned to the same JVM platform?

If anything, we'd like to get to a point where `maxPercentDifference` goes away.  At the moment, it's a hack to resolve pixel diffs -- the provided repro project is a perfect example of this (note the blue diff pixels).

<img width="920" alt="Screen Shot 2022-07-29 at 12 19 15 AM" src="https://user-images.githubusercontent.com/1868149/181682175-0f4feb15-1c42-43dd-bb11-f3b9e8442b90.png">

However, relying on it for record can also result in false security if an icon change or tint color is subtle enough!
