### ISSUE TITLE
Support Compose LocalInspectionMode

### ISSUE THREAD

**Issue by yschimke** [cashapp/paparazzi#508]
**Description**

LocalInspectionMode allows composables to present nicely in previews, even when layout or images are not immediately available.

See https://github.com/coil-kt/coil/blob/70300e5909a561d7e1026c660b8f28be3f0051a6/coil-compose-base/src/main/java/coil/compose/AsyncImagePainter.kt#L148

Also https://cs.android.com/androidx/platform/frameworks/support/+/androidx-main:wear/compose/compose-material/src/commonMain/kotlin/androidx/wear/compose/material/ScalingLazyColumn.kt;l=404?q=ScalingLazyColumn

It would be nice to default this, and also allow specifying to paparazzi.gif or paparazzi.snapshot.

**Additional information:**
- Paparazzi Version: 1.0

**Comment by hlandim** [comment]
I managed to overcome it by mocking the LocalInspectionMode with mockk
```
        paparazzi.snapshot {
            mockkStatic("androidx.compose.ui.platform.InspectionModeKt")
            every { LocalInspectionMode } returns staticCompositionLocalOf { true }
            MyComposableScreen()
        }
```

**Comment by yschimke** [comment]
I think this works without mocking, but the original request was whether this should be done automatically, so components that might use the network such as image loaders might use more useful defaults.

        paparazzi.snapshot {
            CompositionLocalProvider(LocalInspectionMode provides true) {
              MyComposableScreen()
            }
        }

**Comment by yschimke** [comment]
Another example https://github.com/cashapp/paparazzi/issues/735

**Comment by adamalyyan** [comment]
Our stance is that Paparazzi shouldn't set LocalInspectionMode globally as the goal is to provide a snapshot of the true production output. Some Composables, such as `GoogleMap()`, check for `LocalInspectionMode` to short-circuit to a `@Preview`-safe Composable and others may use this flag to show debug layouts/information which means the snapshot is no longer showing what a user would see in production.

Our recommendation is to do what @yschimke mentioned and wrap the composable with a CompositionLocalProvider and set LocalInspectionMode for your individual composable that require it. The linked PR will add a section to the README highlighting this.

**Comment by adamalyyan** [comment]
Related to #709
