### ISSUE TITLE
Feature request: snapshot just the composable

### ISSUE THREAD

**Issue by ember-rose** [cashapp/paparazzi#514]
Android Studio can render composables with the `@Preview` annotation with the render canvas sized to fit the composable or the dimensions specified in the preview annotation. It would be nice to have an API in Paparazzi that exposes this functionality to enable taking snapshots that shrink to the size of the composable or dimensions specified to the snapshot method instead of capturing the whole virtual device.

**Comment by mshearer123** [comment]
+1

**Comment by andersu** [comment]
See https://github.com/cashapp/paparazzi/issues/383 and https://github.com/cashapp/paparazzi/issues/37

**Comment by ember-rose** [comment]
This is a duplicate of #37, thanks!

**Comment by jrodbx** [comment]
Fixed in #497
