### ISSUE TITLE
Creating a base paparazzi test or helpers is not possible

### ISSUE THREAD

**Issue by mshearer123** [cashapp/paparazzi#532]
As far as I understand android modules can only share main code cross module.

To create some sort of base test class or helper methods (to remove some of the boiler plate in setting up compose theme etc), these would need to be in the regular code folders, then another module can add them via testImplementation(<module>).

However as the paparazzi plugin adds to `testImplementation` in all cases, this isn't possible.   

Any suggestions how this could be done?

**Comment by luis-cortes** [comment]
Can you share more details about exactly what type of boilerplate you're trying to avoid? 

Internally we do have wrappers around `Paparazzi` which decorate it and also serve as a way to centralize app specific configuration. There's nothing preventing you from declaring an `api "app.cash.paparazzi:paparazzi:$paparazziVersion"` dependency in your lib (instead of applying the plugin).

**Comment by jrodbx** [comment]
> To create some sort of base test class or helper methods (to remove some of the boiler plate in setting up compose theme etc), these would need to be in the regular code folders, then another module can add them via testImplementation().

If I'm understanding the problem statement correctly, this is a result of how Gradle does things.  There is a concept of [test fixtures](https://docs.gradle.org/current/userguide/java_testing.html#sec:java_test_fixtures) that might prove useful to you, but this isn't a Paparazzi issue.

> However as the paparazzi plugin adds to testImplementation in all cases, this isn't possible.

Not true!  As @luis-cortes mentions, the plugin simply adds the test dependency as a convenience to the consumer, but test modules can also add the same test dependency directly, like so:

```
dependencies {
  api "app.cash.paparazzi:paparazzi:$paparazziVersion"
}
```

**Comment by mshearer123** [comment]
```
dependencies {
  api "app.cash.paparazzi:paparazzi:$paparazziVersion"
}
```

perfect thank you both
