### ISSUE TITLE
Multiple path vectors not loading

### ISSUE THREAD

**Issue by Chrisjc28** [cashapp/paparazzi#542]
**Description**
A complex vector resource doesn't load properly when taking a screenshot.
The project is using compose so it is using the Image composable function and it loading the resource using - 
```
ImageVector.vectorResource(id = R.drawable.test)
```

**Steps to Reproduce**
Steps to reproduce create an android app using compose and a simple composable function which uses the `Image` composable function and load a complex vector with multiple paths.

Try take a screenshot of this function and the vector will not fully load.

**Expected behavior**

When taking a snapshot of the function the vector loads in fine. 

**Additional information:**
- Paparazzi Version: 1.0.0
- OS: Android
- Compile SDK: 33
- Gradle Version: 7.2.2
- Android Gradle Plugin Version: 7.2.2

**Screenshots**

**Comment by dniHze** [comment]
@Chrisjc28 can you verify the same with the latest snapshot build? [This PR](https://github.com/cashapp/paparazzi/pull/471) just landed on master and should be [published](https://github.com/cashapp/paparazzi/actions/runs/3086972777/jobs/4992052146) as the latest snapshot. If it's still reproducing, can you attach the vector file source code? Thanks in advance!

**Comment by jrodbx** [comment]
Closing as fixed
