### ISSUE TITLE
ViewBinding Support

### ISSUE THREAD

**Issue by eschoenawa** [cashapp/paparazzi#544]
**Description**
Paparazzi uses `findViewById` to get references to the Views contained within the inflated layout. However, many modern apps rely on viewBinding to obtain these references to Views. So going back to `findViewById` for the screenshot tests not only feels like using out-of-date architecture, but also introduces inconsistency and is also more error-prone. I'd prefer to access the views in both tests and production code the same way.

**Expected behavior**
Paparazzi should support the use of ViewBinding to obtain references to the views.

**Additional information:**
- Paparazzi Version: 1.0.0

**Comment by JakeWharton** [comment]
The library does not use or require the use of `findViewById`. You are free to obtains view instances in any way you see fit. 

Are you referring to the samples which use `findViewById`?

**Comment by eschoenawa** [comment]
But don't I need to inflate the view using the library? How can I obtain a binding instance when I can't use `Binding.inflate`?

**Comment by JakeWharton** [comment]
The `Paparazzi` instance exposes a `LayoutInflater` through the `layoutInflater` property that you can use to call `Binding.inflate`.

**Comment by eschoenawa** [comment]
Ah, lovely! Thanks for the pointer, that solves it.

Maybe a view binding sample would give this more visibility. I somehow missed the `layoutInflater` property.

**Comment by JakeWharton** [comment]
Yes, indeed. The samples using `findViewById` should be migrated.
