### ISSUE TITLE
Coil images not rendering correctly

### ISSUE THREAD

**Issue by JulianEggers** [cashapp/paparazzi#553]
**Description**
Paparazzi does not render Coil-Images under special circumstances:
- Using coils `AsyncImage` within a `LazyColumn` works with paparazzi.
- However, it stops working whenever prior to that another paparazzi test is launched.

**Steps to Reproduce**

Some notes regarding the code sample: 
- I  assume this behavior is influenced by the order in which tests are executed and it seems like the order in my case is: `a()` then `aa()` then `aaa()`. (?)
- Removing the a-function results in 'aa' being the first snapshot that is being created. -> Rendering the image works.
- Re-adding the a-function results in 'a' being the first snapshot and 'aa' the second. -> Rendering the 'aa'-snapshot stops working (image missing). 
- aaa-function always works
- aaa-function also works when wrapping the image into a Column.

In short:
- This bug only occurs when working with coil images (not normal compose images) wrapped into a LazyLayout (like LazyColumn) and only when prior to that another paparazzi test is launched.

```kotlin
class ExampleUnitTest {

    @get:Rule
    val paparazzi = Paparazzi( )

    /**
    * Running a() first makes aa() not render the image.
    */
    @Test
    fun a() {
        paparazzi.snapshot {
        }
    }

    /**
    * aa() does not work when run second.
    * aa() does work when run as first test.
    */
    @Test
    fun aa() {
        paparazzi.snapshot {
            LazyColumn {
                item {
                    val imageRequest = ImageRequest.Builder(LocalContext.current)
                        .fallback(ColorDrawable(Color.CYAN))
                        .build()

                    AsyncImage(
                        model = imageRequest,
                        contentDescription = null,
                        contentScale = ContentScale.Crop,
                        modifier = Modifier.height(180.dp)
                    )
                }
            }
        }
    }

    /**
    * aaa() always works.
    */
    @Test
    fun aaa() {
        paparazzi.snapshot {
            val imageRequest = ImageRequest.Builder(LocalContext.current)
                .fallback(ColorDrawable(Color.CYAN))
                .build()

            AsyncImage(
                model = imageRequest,
                contentDescription = null,
                contentScale = ContentScale.Crop,
                modifier = Modifier.height(180.dp)
            )
        }
    }
}
```
(Using `implementation "com.google.accompanist:accompanist-drawablepainter:0.24.13-rc"` to create drawables)

**Expected behavior**
Paparazzi should always render coil images within a LazyColumn.

**Additional information:**
- Paparazzi Version: 1.0.0
- Coil: "io.coil-kt:coil-compose:2.0.0", "io.coil-kt:coil-base:2.0.0" (also most recent rc)
- Compose: 1.2.0
- OS: macOS Monterey (12.5 (21G72))
- Compile SDK: 32
- Gradle Version: 7.5
- Android Gradle Plugin Version: 7.2.2

(I tested this on various versions and it seems to be not related to any specific dependency/version.)

**Comment by BenTilbrook** [comment]
I don't think this is fixed. Attached is a sample project with 3 tests with a similar structure described in this issue. Each test should produce a different colored rectangle. However, some do not. 

[PaparazziCoilRenderIssue.zip](https://github.com/cashapp/paparazzi/files/10161979/PaparazziCoilRenderIssue.zip)

**Comment by BenTilbrook** [comment]
@JulianEggers have you been able to verify the fix yourself?

**Comment by JulianEggers** [comment]
We had to disable paparazzi temporarily in our project because of some incompatibilities that occurred after updating our dependencies meaning I can't test this right now.
But I'll report back as soon as paparazzi is running again.

**Comment by TWiStErRob** [comment]
@JulianEggers tip: you can just check out a known working/failing commit in the past, don't have to use latest.
