### ISSUE TITLE
The inputs of PrepareResourcesTask are misconfigured

### ISSUE THREAD

**Issue by cesar1000** [cashapp/paparazzi#560]
**Description**
`mergeResourcesOutput`, `mergeAssetsOutput` and `platformDataRoot` are declared as file inputs with relative path sensitivity, which causes Gradle to compute those inputs based on the file contents. The task, however, consumes the paths, not the contents. As a result, the task will continue to be up-to-date if files are moves to a new location, making the resulting resources file stale.

**Steps to Reproduce**
Run Paparazzi tests on a project, move the project to a new location, run tests again. Resources can no longer be found, and tests will fail with an obscure exception.

**Expected behavior**
All three inputs should be of type string, representing the paths to the files, not the files themselves.

**Additional information:**
- Paparazzi Version: 1.0.0

**Comment by liutikas** [comment]
https://github.com/cashapp/paparazzi/pull/536 fixes the platformDataRoot part. It will become a dependency on the test task directly. The contents do matter for the `Test` task.

I agree that `mergeResourcesOutput` and `mergeAssetsOutput` should be treated as string inputs given that the `Test` task already takes these as inputs, although i'd argue that https://github.com/cashapp/paparazzi/blob/master/paparazzi/paparazzi-gradle-plugin/src/main/java/app/cash/paparazzi/gradle/PaparazziPlugin.kt#L156 needs to be updated to make it not path sensitive.

**Comment by cesar1000** [comment]
One alternative to consider is to not use a resource file at all, and instead just pass in all configuration in system properties. Splitting the configuration to a separate task feels unnecessarily and, and the end of the day, the path to the resource file is passed in as a system property already, so it makes no significant difference.
