### ISSUE TITLE
org.jetbrains.kotlin.backend.common.BackendException : Backend Internal error: Exception during file facade code generation

### ISSUE THREAD

**Issue by DusilB** [cashapp/paparazzi#568]
**Description**
Unable to run snapshot tests. It looks like the failure is in Environment.kt. `!platformDirPath.exists()` throws 

```
org.jetbrains.kotlin.backend.common.BackendException : Backend Internal error: Exception during file facade code generation
File being compiled: mock:///fragment.kt
The root cause java.lang.IllegalStateException was thrown at: org.jetbrains.kotlin.codegen.state.KotlinTypeMapper$typeMappingConfiguration$1.processErrorType(KotlinTypeMapper.kt:127)
```

I have confirmed the path that it's looking for exists and has the required android-platform version

**Expected behavior**

**Additional information:**
- Paparazzi Version: 0.9.3
- OS: macOS Monterey
- Compile SDK: 31
- Gradle Version: 7.1.3
- Android Gradle Plugin Version:

**Comment by jrodbx** [comment]
There's not enough information in this issue to take action on.  Please help maintainers with samples/repros/failing tests.
