### ISSUE TITLE
Paparazzi conflicts with kotlin-android-extensions when using AGP 7.3.0

### ISSUE THREAD

**Issue by agherschon** [cashapp/paparazzi#592]
**Description**
In our project, `module-a` uses `paparazzi`:
```
plugins {
    (...)
    alias(libs.plugins.paparazzi)
}
```
`module-b` doesn't use `paparazzi` (yet) but still uses `kotlin-android-extensions`:
```
plugins {
    (...)
    id("kotlin-android-extensions")
}
```

Then we get the following error:
```
FAILURE: Build failed with an exception.

* What went wrong:
The Android Gradle plugin supports only kotlin-android-extensions Gradle plugin version 1.6.20 and higher.
The following dependencies do not satisfy the required version:
project ':module-b' -> app.cash.paparazzi:app.cash.paparazzi.gradle.plugin:1.0.0 -> app.cash.paparazzi:paparazzi-gradle-plugin:1.0.0 -> org.jetbrains.kotlin:kotlin-gradle-plugin:1.6.10
```

**Steps to Reproduce**
Set your AGP to `7.3.0`

**Expected behavior**
- No issues to use Paparazzi with kotlin-android-extensions

**Additional information:**
- Paparazzi Version: 1.0.0
- OS: MacOS
- Compile SDK: 31
- Gradle Version: 7.5.1
- Android Gradle Plugin Version: 7.3.0

Thank you in advance 🙏🏻

**Comment by jrodbx** [comment]
Please provide a minimal sample project.

**Comment by agherschon** [comment]
Looks like `1.1.0` fixes the issue.
