### ISSUE TITLE
Getting multiple errors in multi module setup

### ISSUE THREAD

**Issue by vivart** [cashapp/paparazzi#600]
**Description**
In my project we have multiple modules. I am trying to add paparazzi to one module.
I have added classpath to the main build.gradle and gradle apply paparazzy to the feature1/build.gradle.
I am getting this error
* What went wrong:
A problem occurred configuring project ':feature1’.
> Failed to notify project evaluation listener.
   > java.lang.IllegalArgumentException: Cannot change attributes of dependency configuration ':feature1:flavour1DebugAndroidTestCompileClasspath' after it has been resolved
   > KotlinJvmAndroidCompilation with name ‘flavour1DebugAndroidTest' not found.

**Comment by jrodbx** [comment]
Please share a sample.  Both CashApp and Register have 500+ modules and use paparazzi in a subset of modules.  

Without more information, I _suspect_ this is related to either another plugin or Paparazzi 1.0 eagerly realizing tasks.  If the latter, Paparazzi 1.1 has the fix.  If the former, then another plugin is causing this issue.

**Comment by vivart** [comment]
Right, some other plugin was causing the issue. Upgrading all the plugins resolved the problem. thanks.
