### ISSUE TITLE
Bump LayoutLib to Electric Eel beta for SDK 33 support

### ISSUE THREAD

**Issue by jrodbx** [cashapp/paparazzi#604]
Electric Eel provides API 33 support, which is blocking us from bumping AndroidX and other dependencies which are coupled to that SDK level.

**Comment by ZacSweers** [comment]
Thoughts on cutting something like a `1.1.0-2022.1-beta02` that folks could use with no guarantees?

**Comment by chrisbanes** [comment]
Just a data point, I quickly tried out @liutikas's PR to bump up layoutlib (#604) last week, but I couldn't get resource loading to work. I planned on taking another look this week, but I think it's related to #524
