### ISSUE TITLE
Broken screenshots generated from previews

### ISSUE THREAD

**Issue by iamutkarshtiwari** [cashapp/paparazzi#620]
**Description**
I have followed David Vavra's showkase and paparazzi [integration approach](https://github.com/davidvavra/showkase-screenshot-tests) to setup screenshot test on my project.
Everything works seamless. I am able to detect visual regression with `./gradlew verifyPaparazziDebug`.

There are two things that seems off and it's with images generated for some previews.

**First:**
Screenshots generated for previews that don't match the vertical size of the screen (meaning they wrap content height) seem distorted/broken. I can assure you that there is no issue with the actual component that is being previewed in Android Studio. It's just that for some reason the image generated from the preview is broken.
For reference I am attaching comparison shots for two different previews:

| Actual Preview in Android Studio | Generated png file |
|--|--|
<img src="https://user-images.githubusercontent.com/6258810/196621809-5db93b61-6800-4df6-b34c-e1557b534225.png" width="300"/> | <img src="https://user-images.githubusercontent.com/6258810/196622007-9053c27b-0e54-481c-ac23-aca34645e83b.png" width="300"/>
<img src="https://user-images.githubusercontent.com/6258810/196621820-b9751557-c020-45a1-92a3-99b51918e114.png" width="300"/> | <img src="https://user-images.githubusercontent.com/6258810/196621995-7ead000f-4560-4254-a991-0215da7a060d.png" width="300"/>

**Second:**

Generated images for Preview methods that are too long for the device screen are cropped:

| Actual Preview in Android Studio | Generated png file |
|--|--|
<img src="https://user-images.githubusercontent.com/6258810/196625665-4b4fda47-1e46-43cb-8cde-7de91255c75c.png" width="300"/> | <img src="https://user-images.githubusercontent.com/6258810/196625641-e83d7cd5-b4e1-4e05-b5e7-eddf332b2845.png" width="300"/>

Here is my ComposePaparazziTest setup: https://gist.github.com/iamutkarshtiwari/afdad2cda63f114120a6fb780ca9f807

Please let me know if I am missing anything. Thank you!

**Additional information:**
- Paparazzi Version: ` 1.0.0`
- OS: 
- Compile SDK:
- Gradle Version:
- Android Gradle Plugin Version:

**Comment by jisungbin** [comment]
In the first case, see: https://github.com/cashapp/paparazzi/issues/37

**Comment by iamutkarshtiwari** [comment]
> In the first case, see https://github.com/cashapp/paparazzi/issues/37.

@jisungbin Thank you for your response. Sorry, I don't understand. Do you mean there is a solution to this issue or is it yet to be fixed in the library?

**Comment by jrodbx** [comment]
Fixed in #497
