### ISSUE TITLE
AGP 8.0.0-alpha08 enables non-transitive R class behavior by default

### ISSUE THREAD

**Issue by alexvanyo** [cashapp/paparazzi#632]
If the property `android.nonTransitiveRClass` is not specified in `gradle.properties`, then the default behavior is governed by the Android Gradle Plugin. As of `8.0.0-alpha08`, the default behavior [switched](https://cs.android.com/android-studio/platform/tools/adt/idea/+/mirror-goog-studio-main:project-system-gradle/src/org/jetbrains/android/refactoring/namespaces/MigrateToNonTransitiveRClasses.kt;l=143;drc=fddeb75fa2cc43f57ea06a0e5f64212ce86507cc) to be `true`, instead of `false`, if the property isn't specified.

This change in behavior results in Paparazzi tests breaking upon upgrade to AGP 8.0.0-alpha08 with a `ResourceNotFoundException` if `android.nonTransitiveRClass` is not declared, I believe because the default value is [assumed to be false](https://github.com/cashapp/paparazzi/blob/a1a723280cc67fe20cda8c8d33f4dde8de91e1f5/paparazzi/paparazzi-gradle-plugin/src/main/java/app/cash/paparazzi/gradle/PaparazziPlugin.kt#L99) (which was the case until now)

The workaround is to explicitly declare `android.nonTransitiveRClass=true` in `gradle.properties`, so that Paparazzi can adjust behavior accordingly.

Potentially Paparazzi could also use the AGP version to check what the default value should be?

**Comment by TWiStErRob** [comment]
AGP 8.0 is released stable.
