### ISSUE TITLE
snapshot test fails when using HTML text with b-Tags in paparazzi 1.2 (snapshot version)

### ISSUE THREAD

**Issue by hardysim** [cashapp/paparazzi#659]
**Description**
Snapshot tests fail when using a compose `Text()` filled with an `AnnotatedString` which includes a bold span (italic, underlined etc. work fine).

Maybe it's related to *layoutlib* (via a newer AGP version?) because this error occurs in the Android Studio preview as well when using Electric Eel (and Flamingo). I've already created a bug at https://issuetracker.google.com/issues/262773698 but maybe you guys here have another view on it.

**Steps to Reproduce**
Please have a look at the bug report above. There's also a link with an example project and the error stacktrace. It's the same for the AS preview and the failed paparazzi test.

**Expected behavior**
The snapshot should still be generated and show the bold text.

**Additional information:**
- Paparazzi Version: 1.2.0-20221214.164218-18
- OS: 
- Compile SDK: 33
- Gradle Version: 7.5 and 7.6 tested
- Android Gradle Plugin Version: AGP `7.3.1` is working but paparazzi `1.2.0-20221214.164218-18` overrides it to `7.4.0-rc01`

**Screenshots**
|AS dolphin|AS electric eel|
|-|-|
|![image](https://user-images.githubusercontent.com/3737512/208112412-7b52bba1-ea49-41b8-9d24-0f4de865c994.png)|![image](https://user-images.githubusercontent.com/3737512/208112460-13fb0397-7607-4d12-8de1-09a1173c38be.png)|

**Comment by jrodbx** [comment]
Latest uses Electric Eel's layoutlib, so this adds up.  I'll close this for now, as the referenced issue likely points to it being an issue inherited from layoutlib.
