### ISSUE TITLE
Memory leak caused when calling paparazzi.snapshot

### ISSUE THREAD

**Issue by sorinirimies** [cashapp/paparazzi#660]
**Description**
There is a memory leak caused by calling `paparazzi.snapshot`, even though there are clean up methods being called within the paparazzi implementation.
Even the Paparazzi instance is recreated for every test. `Showkase` or the `TestParameter` are not the reason either. Removing them has no effect on the memory leak.

**Steps to Reproduce**
Running:
```val runtime = Runtime.getRuntime()

@Test
fun screenshotTests(...) {
  ...
  System.gc()
  println("Memory: ${runtime.totalMemory() - runtime.freeMemory()}")
}
```
Gets the output:

Memory: 162554496
Memory: 163915984
Memory: 165186320
...
Memory: 508340192
Memory: 509459232
Memory: 510582816

**Expected behavior**
Memory output shouldn't increase exponentially keeping references.

**Additional information:**
- Paparazzi Version: `dev.chrisbanes.paparazzi:paparazzi-gradle-plugin:1.1.0-sdk33-alpha02` 
- OS: Android 13
- Compile SDK: 
- Gradle Version:7.6
- Android Gradle Plugin Version: `7.3.1`

**Screenshots**

**Comment by jrodbx** [comment]
The heap size is growing but have you run this in a memory profiler to ascertain the source of the leaks?  An hprof or VisualVM screenshot would help a lot here.

**Comment by sorinirimies** [comment]
No, our CI/CD started failing with the out of memory exception. After deactivating the screenshot tests the memory leak is gone.

**Comment by jrodbx** [comment]
Closing due lack of data pointing to the issue.  Please reopen if you can provide more info.

**Comment by sorinirimies** [comment]
Mhh, not sure exactly what more data we should provide. I have some logs from the CI/CD. 
But we ran several tests locally, with the same results.
