### ISSUE TITLE
Using paparazzi with custom binding component

### ISSUE THREAD

**Issue by jaroslavhavelik** [cashapp/paparazzi#666]
**Description**
Impossible to use paparazzi with custom binding that is provided via Hilt's custom binding component.

**Steps to Reproduce**
Create a setup similar to this one: https://github.com/nuhkoca/HiltDataBindingSample.

Running paparazzi results in the following error:
`A BindingAdapter in com.example.hiltdatabindingdemo.binding.ImageBindingAdapter is not static and requires an object to use, retrieved from the DataBindingComponent.`

**Possible workaround**
Change `ImageBindingAdapter` to `object` and annotate `fun ImageView.bindImage` with `@JvmStatic`

**Need help**
Is there any other way to make this setup work? Making `ImageBindingAdapter` `object` doesn't feel right (especially if we want to pass other parameters to this class, e.g. custom image cache key provider)

**Comment by jrodbx** [comment]
I'm not familiar with Hilt's custom binding component, but can you elaborate on how this is a Paparazzi issue?  At first thought, this seems more like a Hilt configuration issue.

The link you provided has no mention of paparazzi.  Please open a new issue with a branch to a repro.
