### ISSUE TITLE
Showkase + Paparazzi - Failed to transform layoutlib-native-jdk11-2022.1.1-beta4-f5f9f71.jar

### ISSUE THREAD

**Issue by vinaygaba** [cashapp/paparazzi#669]
**Description**
I'm working on an artifact that automates screenshot testing for Compose projects using Showkase + Paparazzi. It picks up all your previews automatically and auto generates a paparazzi test to screenshot test all the previews with minimal setup. Here's the PR for it - https://github.com/airbnb/Showkase/pull/294

I have everything working but seeing this error on the `mergeExtDexDebug` step. For the artifact I'm creating, I'm using the paparazzi and layoutlib dependency [explicitly](https://github.com/airbnb/Showkase/pull/294/files#diff-7db95a780683cb3714ba262791291343ebab56c0dc847216b7ced408125cafc3R82) instead of using the plugin since it needs to live in the main source set and the plugin assumes the test source set. 

I'm obviously missing some additional setup so would love some insights on what else I would need to do to make it happen 🙏 

```
> Could not resolve all files for configuration ':showkase-screenshot-testing-paparazzi:debugAndroidTestRuntimeClasspath'.
   > Failed to transform layoutlib-native-jdk11-2022.1.1-beta4-f5f9f71.jar (app.cash.paparazzi:layoutlib-native-jdk11:2022.1.1-beta4-f5f9f71) to match attributes {artifactType=android-dex, asm-transformed-variant=NONE, dexing-enable-desugaring=true, dexing-is-debuggable=true, dexing-min-sdk=21, org.gradle.category=library, org.gradle.libraryelements=jar, org.gradle.status=release, org.gradle.usage=java-runtime}.
      > Execution failed for DexingWithClasspathTransform: /Users/vinaygaba/.gradle/caches/modules-2/files-2.1/app.cash.paparazzi/layoutlib-native-jdk11/2022.1.1-beta4-f5f9f71/81a8652b068c130269c1070f7b884628e919db38/layoutlib-native-jdk11-2022.1.1-beta4-f5f9f71.jar.
         > Error while dexing.
```

**Steps to Reproduce**
Pull this branch - https://github.com/airbnb/Showkase/pull/294
and run this command `./gradlew :showkase-screenshot-testing-paparazzi:mergeExtDexDebugAndroidTest`

**Expected behavior**
No build errors

**Additional information:**
- Paparazzi Version: 1.1.0
- OS: Mac
- Compile SDK: 32
- Gradle Version: 
- Android Gradle Plugin Version: 7.2.1

**Comment by JakeWharton** [comment]
Paparazzi is a library that only runs on the JVM yet you appear to be attempting to bundle it inside an Android library.

**Comment by vinaygaba** [comment]
@JakeWharton that makes sense. Sounds like I need to bundle another artifact that exposes Paparazzi inside a JVM library and then reference it inside the Android library 🤔 Either that or Paparazzi plugin adds first class support for the main source set (related feature request https://github.com/cashapp/paparazzi/issues/561). What do you think is the best course of action?

**Comment by vinaygaba** [comment]
hmm thinking about this more, I'm not sure my option 1 would work either. Going to give it a shot regardless but open to any other suggestions you might have...

**Comment by JakeWharton** [comment]
Paparazzi in the main source set only makes sense if you are building a JVM library whose target usage will be in the host-side test source sets of Android modules. It will not magically allow you to use it in an Android library's main source set (either directly or via a dependency). If you must go this route then you could use a `compileOnly` dependency with a no-op `runtime` dependency (and obviously the real dependency on the test classpath).

However, if the goal is to enumerate all `@Preview` annotations from the main source set from within the test source then you probably want to look at different solutions. You could use UAST to parse sources and discover them like the IDE would, you could generate a list into Java resources from the main source set and then consume that list as a resource from the test, or use reflection-based classpath scanning to find them. But how to do that isn't a paparazzi problem but a general problem.

**Comment by vinaygaba** [comment]
The only reason I even need this dependency in the main source set is so that I can expose it as an artifact on maven. Is there a way to have something in the test sourceset and still expose it on maven? Maybe I should go down the `compileOnly` route and explore that recommendation.

**Comment by TWiStErRob** [comment]
It's not the test sourceset that matters, I think. It's the dependencies and what you're compiling for what target. Taking a step back: Your error is in androidTest dexing. Do you need to UI test this module you're compiling (considering it's Paparazzi related)? Does it actually have to be an AAR/APK? Or is this the sample project you're trying to compile? compileOnly and runtimeOnly are really powerful, do give it a try! Have a think about what is necessary for which compilation/execution and you might be able to simplify.

---

Also note that your build.gradle, however you compile and build, and the POM you publish doesn't have to have a 1:1 mapping. You can do whatever you want with the POM with simple Gradle APIs, for example: https://github.com/TWiStErRob/net.twisterrob.gradle/blob/96db65018a3afa2b0d89f2b81dc68ac696cadb28/gradle/plugins/src/main/kotlin/net/twisterrob/gradle/build/PublishingPlugin.kt
(Do this as a last resort though, because it's hell to maintain pom hacks.)

**Comment by vinaygaba** [comment]
@TWiStErRob thanks for adding your insights. 

> Your error is in androidTest dexing. Do you need to UI test this module you're compiling

This module does not need to be run androidTest at all. The only reason this runs is because I've setup my CI to execute `./gradlew connectedCheck`. Is there a way to skip `androidTest` gradle stuff for a particular module?

> Does it actually have to be an AAR/APK
Yes it does need to be a library artifact that I upload on maven, along with the other artifacts in Showkase

I did try `compileOnly` and that seems to do the trick! Thanks for the tip (and also to Jake who suggested the same thing earlier)  🙏 

The users of the artifact are expected to add the Paparazzi plugin so at runtime the correct dependencies will be available.

**Comment by TWiStErRob** [comment]
> Yes it does need to be a library artifact that I upload on maven

You can upload jars and aars from the same project for different modules. A maven artifact in the Android world doesn't have to be aar, unless you actually need to use Android APIs, or publish resources.

> Is there a way to skip androidTest gradle stuff for a particular module?

I don't remember if it is possible to disable the androidTest build. No luck in Google and ChatGPT said `android.defaultConfig.testInstrumentationRunner = null`, but I can't find evidence other than the property is actually nullable 😮; I'm AFK so can't try.

In the past with similar issues, what I usually did is either:
 * specify Gradle tasks more specifically on command line (of CI)
 * created my own lifecycle task and added dependencies conditionally, something like: `dependsOn(rootProject.allProjects.filter { it.path != ... }.map { it.path + ":taskName" }`
 * probably the easiest: `gradlew connectedCheck -x :foo:bar:connectedCheck`

**Comment by vinaygaba** [comment]
@TWiStErRob This in fact does need to be an aar since I have android specific logic in the artifact

Clearly, I should be suing ChatGPT even more since I never found this tip on Google 😅

**Comment by vinaygaba** [comment]
Thanks for your help everyone. Closing this issue as using a `compileOnly` dependency solved my problem!

**Comment by TWiStErRob** [comment]
Did setting it null actually worked?
