### ISSUE TITLE
Is there a way to generate a snapshot for different combinations

### ISSUE THREAD

**Issue by hellosagar** [cashapp/paparazzi#671]
Right now, for example a `composable` function takes 4 variable and each variable have 2 states, right now Ive to write 8 functions  to create snapshots for all.

Is there is a cleaner way to do this?

**Comment by JakeWharton** [comment]
We use https://github.com/google/TestParameterInjector/. In general, this is a JUnit/testing question and not one specific to paparazzi.

**Comment by hellosagar** [comment]
Apologies and thanks a lot.

**Comment by JakeWharton** [comment]
No worries. I more meant this technique is generally applicable so it works for more than just paparazzi.

**Comment by hellosagar** [comment]
Sure thing, also receiving a reply from my inspiration since i started android development already means a lot ♥️🙏 as you took the time to reply
