### ISSUE TITLE
Breaking tests if androidx.savedstate is not added in dependency

### ISSUE THREAD

**Issue by jk-groww** [cashapp/paparazzi#686]
**Description**
I updated the paparazzi to version 1.2.0 from 1.1.0, and the test started breaking. Following is the error message:
```
Companion
java.lang.NoSuchFieldError: Companion
	at app.cash.paparazzi.internal.PaparazziSavedStateRegistryOwner.<init>(PaparazziViewOwners.kt:20)
	at app.cash.paparazzi.Paparazzi.takeSnapshots(Paparazzi.kt:294)
	at app.cash.paparazzi.Paparazzi.snapshot(Paparazzi.kt:200)
	at app.cash.paparazzi.Paparazzi.snapshot$default(Paparazzi.kt:199)
```

**Steps to Reproduce**
Update the version of the paparazzi from 1.1.0 to 1.2.0 in a project with the following dependencies.
```
    implementation(project(":lib"))
    implementation(project(":lib-demo"))
//    implementation("androidx.savedstate:savedstate:1.2.0")
    testImplementation("junit:junit:4.13.2")
    testImplementation("com.google.testparameterinjector:test-parameter-injector:1.9")
    androidTestImplementation("androidx.test.ext:junit:1.1.3")
    androidTestImplementation("androidx.test.espresso:espresso-core:3.4.0")
```
In project lib and lib-demo there is one API dependency
```
api("androidx.appcompat:appcompat:1.3.0")
```

**Expected behavior**
Should have worked after the version update.

I had to add this dependency to make it work
```
implementation("androidx.savedstate:savedstate:1.2.0")
```

**Additional information:**
- Paparazzi Version: 1.2.0
- OS: Mac OS
- Compile SDK: 32
- Gradle Version: 7.3.3
- Android Gradle Plugin Version: 7.2.2

**Screenshots**
NA

**Comment by jrodbx** [comment]
@saket this is expected behavior right?  i.e., something should be providing the dependency?

@jk-groww 
> Update the project from 1.1.0 to 1.2.0

What project?  Can you please provide a MRE?

**Comment by jk-groww** [comment]
here is repository to recreate the issue. https://github.com/jk-groww/PaparazziIssue686. All the tests pass in the lib if the paparazzi version is 1.1.0.

**Comment by saket** [comment]
@jk-groww this is very helpful, thanks! I'll investigate what's happening here.
