### ISSUE TITLE
Custom views using ColorStateList fail

### ISSUE THREAD

**Issue by faogustavo** [cashapp/paparazzi#715]
**Description**
Taking snapshots on view using ColorStateList fails.

```
INFO: ResourcesCompat [3]: Failed to inflate ColorStateList, leaving it to the framework
java.lang.NullPointerException
	at androidx.core.content.res.ColorStateListInflaterCompat.createFromXml(ColorStateListInflaterCompat.java:95)
	at androidx.core.content.res.ResourcesCompat.inflateColorStateList(ResourcesCompat.java:262)
	at androidx.core.content.res.ResourcesCompat.getColorStateList(ResourcesCompat.java:236)
	at androidx.core.content.ContextCompat.getColorStateList(ContextCompat.java:558)
```

**Steps to Reproduce**

```kt
val boxStroke = AppCompatResources.getColorStateList(context, R.color.input_border)
textInputLayout.setBoxStrokeColorStateList(boxStroke)
```

**Project to reproduce**

Project: [faogustavo/PaparazziRepro](https://github.com/faogustavo/PaparazziRepro)
Custom View: [BugTextInput.kt](https://github.com/faogustavo/PaparazziRepro/blob/main/paparazzi-bugs/src/main/java/com/example/paparazzi_bugs/BugTextInput.kt)
Test: [BugTextInputTest.kt](https://github.com/faogustavo/PaparazziRepro/blob/main/paparazzi-bugs/src/test/java/com/example/paparazzi_bugs/BugTextInputTest.kt)

**Expected behavior**
Test run without breaking

**Additional information:**
- Paparazzi Version: 1.2.0
- OS: MacOS
- Compile SDK: 33
- Gradle Version: 7.5
- Android Gradle Plugin Version: 7.4.1

**Screenshots**

![image](https://user-images.githubusercontent.com/7588480/218491311-2913859b-3c11-4bb1-a806-92fcdde24d13.png)

**Comment by martirius** [comment]
Same error here, but just with inflating the View that has a `<selector>` as a background.
I noticed also that I receive this error only if test are launched from Android Studio and not directly from terminal.
But in my case tests pass and the report is generated

**Comment by nicbell** [comment]
I'm seeing the same with a tinted `MaterialCardView`.

**Comment by ashley-figueira** [comment]
I'm getting the same with a `CollapsingToolbarLayout`.

**Comment by lbautista-ta** [comment]
I'm seeing the same - any thoughts on a fix? Seems like a glaring bug

**Comment by nicbell** [comment]
@lbautista-ta updating layoutlib may help, currently I think Paparazzi is using a beta of Electric Eel maybe this is buggy. I'm not sure though.

**Comment by julenminer** [comment]
I haven’t found a solution to this problem, but I gathered some information and found how to reproduce this with few steps.

The problem starts to appear when I add the appcompat library to my dependencies, from 1.4.0 and above. Once I add this, just adding a TextView to a layout, and trying to set the app:drawableTint attribute (also the drawableStart, but it is not necessary to see the error) with a color reference (not by setting the hex value) will trigger the exception.

Some other attributes that I found failing are rippleColor and iconTint for buttons.

However, the test seems to work and the verification is done correctly, but the screenshots are being generated every time I run the record command, even though there aren’t any layout changes.

Steps to reproduce in the paparazzi samples project:

1. Add this dependency to the “sample” build.gradle:

```kotlin
implementation 'androidx.appcompat:appcompat:1.6.1'
```

2. Create a new layout resource (I called it bug.xml):

```kotlin
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
  xmlns:app="http://schemas.android.com/apk/res-auto"
  android:layout_width="match_parent"
  android:layout_height="wrap_content"
  android:orientation="vertical">

  <TextView
    android:layout_width="wrap_content"
    android:layout_height="wrap_content"
    android:drawablePadding="4dp"
    android:gravity="center"
    android:text="Búsqueda guardada"
    app:drawableTint="@color/bolt" />

</LinearLayout>
```

3. Create a new test file:

```kotlin
package app.cash.paparazzi.sample

import app.cash.paparazzi.Paparazzi
import app.cash.paparazzi.sample.databinding.BugBinding
import com.android.ide.common.rendering.api.SessionParams
import org.junit.Rule
import org.junit.Test

class BugTest {
  @get:Rule
  val paparazzi = Paparazzi(
    renderingMode = SessionParams.RenderingMode.SHRINK,
    showSystemUi = false
  )

  @Test
  fun default() {
    val binding = BugBinding.inflate(paparazzi.layoutInflater)
    paparazzi.snapshot(binding.root)
  }
}
```

4. Run the test with android studio or the following command:

```kotlin
./gradlew recordPaparazziDebug
```

Thanks! :)

**Comment by jrodbx** [comment]
When I investigated a while back (sorry for not sharing context then!), it appeared then that deeper in the stack trace, the issue was actually related to a NullPointerException in android.os.Build, which is now fixed per https://github.com/cashapp/paparazzi/pull/765.

Closing this issue as fixed, but please re-open/file if the issue still occurs!
