### ISSUE TITLE
layoutlib module clones "the world"

### ISSUE THREAD

**Issue by TWiStErRob** [cashapp/paparazzi#717]
As a contributor I wanted to quickly test something in relation to a PR in this repo.
I ran `gradlew publishToMavenLocal` and that started `cloneLayoutLib`, which took 1.5 hours, only to end with:
```
* What went wrong:
Execution failed for task ':libs:layoutlib:cloneLayoutlib'.
> There is not enough space on the disk
```

I double-checked and the `paparazzi\build\prebuilts\studio\layoutlib\.git` folder is 10G. Is it really necessary to pull everything from the server to only get the 300M of `paparazzi\build\prebuilts\studio\layoutlib\data` we need?

_After writing this report I realized that I should've been more specific about which module I want to pubish..._ the issue still stands, we could achieve a 97% bandwidth and disk space saving. 😅

### Investigation

Out of curiosity how hard this is, I did the following:
```shell
$ git clone https://android.googlesource.com/platform/prebuilts/studio/layoutlib . --depth=1 --single-branch
Cloning into '.'...
remote: Finding sources: 100% (2/2)
remote: Total 2 (delta 0), reused 2 (delta 0)
Receiving objects: 100% (2/2), done.

$ git status
On branch master
Your branch is up to date with 'origin/master'.

$ git fetch origin f5f9f71
fatal: couldn't find remote ref f5f9f71

$ git fetch origin studio-2022.1.1-beta4 --depth 1
remote: Finding sources: 100% (10480/10480)
Receiving objects: 100% (10480/10480), 181.67 MiB | 348.00 KiB/s, done.

Resolving deltas: 100% (2160/2160), done.
From https://android.googlesource.com/platform/prebuilts/studio/layoutlib
 * tag               studio-2022.1.1-beta4 -> FETCH_HEAD
```

That said, this (ab)uses the fact that the repo's `master` just happens to be empty, I tried again and this one command does it all:
```shell
$ git clone https://android.googlesource.com/platform/prebuilts/studio/layoutlib --branch studio-2022.1.1-beta4 --single-branch --depth 1 .
Cloning into '.'...
remote: Finding sources: 100% (10484/10484)
Receiving objects: 100% (10484/10484), 181.67 MiB | 344.00 KiB/s, done.

Resolving deltas: 100% (2160/2160), done.
Note: switching to 'f5f9f71ebf7658a26af18684242501e987968ddb'.

Updating files: 100% (10647/10647), done.
```

**Comment by TWiStErRob** [comment]
I tried with
```toml
[versions]
layoutlib = "2022.1.1-beta4"
```

```groovy
      def tag = "refs/tags/studio-" + libs.versions.layoutlib.get()
      logger.warn('Cloning prebuilt layoutlib: this make take a few minutes...')
      grgit.clone {
        dir = repoDir
        uri = "https://android.googlesource.com/platform/prebuilts/studio/layoutlib"
        branches = [ tag ]
        refToCheckout = tag
      }
```
but it still cloned everything.

---

Additionally I noticed that 'org.ajoberstar.grgit' plugin is not used, so raised https://github.com/cashapp/paparazzi/pull/718.

**Comment by TWiStErRob** [comment]
> @AfzalivE in #718: I recently added the support for shallow clone in [grgit 5.2.0](https://github.com/ajoberstar/grgit/releases) (using the depth argument). Will specifying this also help speed up anything?

Yeah, that will probably help here, even if not fully, it'll be much better. I wonder if `--single-branch` is also supported in grgit, as that would be necessary to use together as far as I can see.

#718 is still a valid orthogonal improvement though.

**Comment by AfzalivE** [comment]
Single branch is also supported with `all = false` + specifying the [list of branches](https://github.com/AfzalivE/grgit/blob/main/grgit-core/src/main/groovy/org/ajoberstar/grgit/operation/CloneOp.groovy#L56). 🙂

**Comment by TWiStErRob** [comment]
Depends on https://github.com/cashapp/paparazzi/pull/841
