### ISSUE TITLE
Ignore Permission request when taking screenshots using a Jetpack Compose UI.

### ISSUE THREAD

**Issue by hlandim** [cashapp/paparazzi#724]
z`I'm using Jetpack Compose UI and I have created a UI with an Androidx Camera Preview.
To do so, I used [accompanist-permissions](https://google.github.io/accompanist/permissions/) to request the Camera Permission.

Problem: 
When taking the screenshots of it, I'm getting the error: 
`Permissions should be called in the context of an Activity`
when calling `rememberPermissionState(Manifest.permission.CAMERA)`

I had faced this problem when I was creating the @Preview function for it and overcome it, checking the flag [LocalInspectionMode.current](https://developer.android.com/jetpack/compose/tooling/studio#localinspectionmode).

Is there a way to do the same on Paparazzi?.

Currently, I'm passing a flag to my screen to ignore it.

**Comment by dniHze** [comment]
It's ideal to use Paparazzi for testing your stateless UI l, where you just forward the state to your compostable, instead of querying it inside. This is also a good approayfor your codebase, in case you'll write automated composable tests.

**Comment by jrodbx** [comment]
@hlandim do you have a sample/repro?  otherwise, I think what hlandim said makes sense.

**Comment by jrodbx** [comment]
Closing as wontfix, the preferred approach would be extract the permissions code out of your UI
