### ISSUE TITLE
onLayoutCompleted doesn't affect the UI

### ISSUE THREAD

**Issue by martirius** [cashapp/paparazzi#725]
This is more a question than an enhancement, but still.

I need to do some UI logic and move a View after a RecyclerView.LinearLayoutManager finished calculating the layout.
Unfortunately it looks like the code inside onLayoutCompleted is called after the screenshot has already been taken/the view has been already rendered.

Is there a way to do so and postpone the screenshot after all calculations end?

**Comment by cpaleop** [comment]
I think I run into a very similar situation, but not sure. My issue originates from the `onTextLayout` of the `Text` composables. `onTextLayout` provides a `TextLayoutResult` with a `lineCount` which I want to use to optionally show a "Read more" button.

The button is rendered on the Preview of the Composable but not on the snapshot, see screenshots attached.

Preview:
![image](https://user-images.githubusercontent.com/16907506/223415279-8a9a5047-47f8-486d-b265-5e06057900d9.png)

Snapshot:
![image](https://user-images.githubusercontent.com/16907506/223415429-fe60b72a-4821-495e-9740-e0f6e4da6fe6.png)

**Comment by jrodbx** [comment]
Can you:
1) try the latest snapshot and see if the recent commits fix this issue?
2) provide a minimal repro example?  repros get prioritized attention/fixes!

**Comment by jrodbx** [comment]
Closing since no answer and no repro provided.  Please refile if this happens again.
