### ISSUE TITLE
Paparazzi environment has compileSdkVersion 32 when compileSdk=33 and targetSdk=32

### ISSUE THREAD

**Issue by lbautista-ta** [cashapp/paparazzi#729]
**Description**
Paparazzi environment has compileSdkVersion 32 when the project uses compileSdk=33 and targetSdk=32 

**Steps to Reproduce**
Using this repo, add targetSdk 32 to `sample/build.gradle`:
```groovy
  compileSdk libs.versions.compileSdk.get() as int /* resolves to 33 */
  defaultConfig {
    minSdk libs.versions.minSdk.get() as int
    targetSdk 32
  }
```

Modify `HelloComposeTest.kt` to add `println(detectEnvironment())`:
```kotlin
  @Test
  fun compose() {
    println(detectEnvironment())
    paparazzi.snapshot { HelloPaparazzi() }
  }
```

Run the test, and the output is:
`Environment( ..., compileSdkVersion=32, ...)`

This can lead to errors in projects with compileSdk=33 and targetSdk=32, for example this issue https://github.com/cashapp/paparazzi/issues/631 manifests despite being fixed in 1.2.0 

Of course you can still force compileSdkVersion 33 by setting the paparazzi environment, but this doesn't look like intended behavior.

**Expected behavior**
`Environment( ..., compileSdkVersion=33, ...)`

**Additional information:**
- Paparazzi Version: 1.2.0
- OS: macOS Ventura 13.2.1
- Compile SDK: 33
- Gradle Version: 7.6
- Android Gradle Plugin Version: 7.4.0

**Comment by Sdssourcing** [comment]
#

**Comment by geoff-powell** [comment]
For now this is expected behavior. Since targetSdkVersion is the sdk target you want your code to run against, so it makes sense to override `Build.SDK_INT` with `targetSdkVersion` defined in your `build.gradle`.

cc @jrodbx if there is context I am missing
