### ISSUE TITLE
Snapshot that receives a view does not recognize changes.

### ISSUE THREAD

**Issue by meligeo** [cashapp/paparazzi#730]
**Description**
I was doing some tests  with paparazzi and i perceive that some type of tests does not work properly.

**Steps to Reproduce**

Mainly, when i use the ` paparazzi.snapshot(view)` the way of make screenshots receiving the view, does not matter what changes i do to the view in the test, the test always pass. here some screen captures:
1) Creating the record of the tests, record finish correctly and success.

<img width="1309" alt="Captura de Pantalla 2023-03-07 a la(s) 2 28 50 p m" src="https://user-images.githubusercontent.com/70920226/223533767-8a5014b5-6066-45ce-9f53-54fc25020d67.png">

2) This is the screenshot created:

<img width="1287" alt="Captura de Pantalla 2023-03-07 a la(s) 2 37 33 p m" src="https://user-images.githubusercontent.com/70920226/223533915-d640eb8d-5576-41fb-a82f-32985413a9f2.png">

3) Here the text of the textview passed have been changed with the text "This is another test Test" (different to the recorded textview text)

<img width="1323" alt="Captura de Pantalla 2023-03-07 a la(s) 2 29 43 p m" src="https://user-images.githubusercontent.com/70920226/223534167-49abf10e-75eb-4c49-aecb-07fa60a4df55.png">

No matter how many changes i apply to the passed  as param view (TextView), test always are successful.

<img width="1167" alt="Captura de Pantalla 2023-03-07 a la(s) 2 40 26 p m" src="https://user-images.githubusercontent.com/70920226/223534537-7fb64472-43bc-4c6e-ade1-483c559bae75.png">

It happens as well using the inflater `paparazzi.inflate<LinearLayout>(R.layout.launch)` but less often though.

This tests have been done in the sample project of paparazzi library.

**Expected behavior**
Test with changes in view should fail

**Additional information:**
This information is on my own project: 
- Paparazzi Version: 1.2.0
- OS: macOS 12.6 (21G115)
- Compile SDK: 32
- Gradle Version: 7
- Android Gradle Plugin Version:

**Screenshots**

**Comment by TWiStErRob** [comment]
What commands were you running? Only the result is visible, but you haven't mentioned the Gradle tasks.

**Comment by jk-groww** [comment]
I have come across a similar issue before. Check if this issue is relevant to you https://github.com/cashapp/paparazzi/issues/703. You can increase the accuracy of the test, which would solve the issue of small changes not failing the test.

**Comment by jrodbx** [comment]
@meligeo I suspect that your issue is that the IDE's gutter Run icon does not the verify task, but rather the testDebug task.  

This has been discussed before; see https://github.com/cashapp/paparazzi/pull/421 for the reasoning.
