### ISSUE TITLE
Paparazzi reflection access is going to break with Compose 1.5

### ISSUE THREAD

**Issue by ShikaSD** [cashapp/paparazzi#738]
**Description**
Paparazzi uses reflection to force recomposer to release all composition related data. In [the change](https://r.android.com/c/platform/frameworks/support/+/2472444/6/external/paparazzi/paparazzi/src/main/java/app/cash/paparazzi/Paparazzi.kt) that just landed to `androidx-main`, we change the type of storage one of the fields use, breaking compatibility.

**How to reproduce**
Use Paparazzi with the latest snapshot of Compose runtime, observe a failed cast on `snapshotInvalidations` field. See [the change](https://r.android.com/c/platform/frameworks/support/+/2472444/6/external/paparazzi/paparazzi/src/main/java/app/cash/paparazzi/Paparazzi.kt) with the suggested fix.

**Comment by ShikaSD** [comment]
@TWiStErRob Errr, the internal redirect breaks everything, fixed now

**Comment by TWiStErRob** [comment]
Now they're the same link... 🕵️‍♂️

**Comment by ShikaSD** [comment]
They point to the same change regardless :)

**Comment by ShikaSD** [comment]
I'd also love to know more about the reason behind this cleanups, maybe we can provide a proper API or fix the original bug if there's one

**Comment by TWiStErRob** [comment]
Ah, I see, this is the change on AndroidX: https://android-review.googlesource.com/c/platform/frameworks/support/+/2472444/6/compose/runtime/runtime/src/commonMain/kotlin/androidx/compose/runtime/Recomposer.kt#202

I'll let @jrodbx and co. answer that.

**Comment by gamepro65** [comment]
It looks like you're referencing an older version of Paparazzi. We've since removed that logic and placed a proper fix https://github.com/cashapp/paparazzi/pull/682
