### ISSUE TITLE
Support for custom Density value

### ISSUE THREAD

**Issue by anhanh11001** [cashapp/paparazzi#773]
<img width="881" alt="Screenshot 2023-05-08 at 16 46 40" src="https://user-images.githubusercontent.com/36192582/236855604-929b609d-d8c5-4c05-a653-0e1d5d0768eb.png">

Feature request: Is it possible to use custom Density value outside this Enum class. For example, `Density = 210`. I'm aware that this class come from standard Android API and not Paparazzi, but still I think it's worth a try asking whether your team has considered something like this or not.

My use case is I'm working on a physical device that my company build which has a custom `dpi`. It's not a standard mobile phone or tablet. We would like to screenshot test this.

The second use case is inside Android Accessibility Service, we have option to change device size. This can lead to the change of density value.

Thanks!

**Comment by sergio-sastre** [comment]
Actually, it is kind of possible to simulate the displaySize option given in the emulator:

```kotlin
enum class DisplaySize(val value: Float) {
    SMALL(0.85f),
    NORMAL(1f),
    LARGE(1.1f),
    LARGER(1.2f),
    LARGEST(1.3f);
}

fun Context.setDisplaySize(displaySize: DisplaySize) =
    this.apply {
        val density = resources.configuration.densityDpi
        val config = Configuration(resources.configuration)
        config.densityDpi = (density * displaySize.value).toInt()
        
        // Although this method is deprecated, it works for this case
        resources.updateConfiguration(config, resources.displayMetrics)
    }
```

Then in your Paparazzi test:
```kotlin
class CoffeeDrinkAppBarHappyPathTest {
    @get:Rule
    val paparazzi = Paparazzi()

    @Test
    fun snapComposable() {
        paparazzi.context.setDisplaySize(DisplaySize.LARGER)

        paparazzi.snapshot(name = "CoffeeDrinkAppBar_DisplaySize_LARGER") {
            AppTheme {
                CoffeeDrinkAppBar()
            }
        }
    }
}
```
If you run this tests with different DisplaySize values, you'll notice the difference

Hope it helps :)

**Comment by anhanh11001** [comment]
Hi, thanks for the tip! It works really nice for me

**Comment by artemyto** [comment]
Starting with 1.3.4, you can do `density = Density.create(n)`. See examples here: https://github.com/cashapp/paparazzi/blob/master/paparazzi/src/main/java/app/cash/paparazzi/DeviceConfig.kt#L309
