### ISSUE TITLE
SwipeRefreshLayout never shows refreshing indicator

### ISSUE THREAD

**Issue by chrisbanes** [cashapp/paparazzi#776]
**Description**
Trying to snapshot a SwipeRefreshLayout with it's refreshing indicator. Unfortunately it never renders the indicator, even when using `InstantAnimationsRule`

**Steps to Reproduce**

``` kotlin
class PullToRefreshTest() {
  @get:Rule
  val paparazzi = Paparazzi()

  @get:Rule
  val instantAnimationsRule = InstantAnimationsRule()

  @Test
  fun swipeRefresh() {
    val view = SwipeRefreshLayout(paparazzi.context).apply {
      setRefreshing(true)
    }
    paparazzi.snapshot(view)
  }
}
```

**Comment by geoff-powell** [comment]
Doing some preliminary debugging it seems the animation clock for legacy Animations `android.view.Animation` (used by SwipeRefreshLayout) is driven by View.java's `AttachInfo.drawingTime`. Currently, this is always being reported as 0 instead of using `Choreographer.getFrameTime(). Looking into how we can get layoutlib to report the correct drawingTime

**Comment by adamalyyan** [comment]
I filed a issue with Google related to the SwipeRefreshLayout using `android.view.Animation` and thus not respecting the systems animation duration scale here: https://issuetracker.google.com/issues/290977133

**Comment by adamalyyan** [comment]
After digging into this we have decided to hold off on a solution until we provide video support in Paparazzi as this will provide a better API surface for issues like this.

**Comment by jrodbx** [comment]
This is now fixed thanks to a combination of two reasons:
1) paparazzi#gif can record multiple frames, and 
2) this layoutlib commit which landed in Iguana (kudos to @geoff-powell for his comment which jogged my memory about this commit): https://android.googlesource.com/platform/frameworks/layoutlib/+/241ba16e136dfa3cabe4dbb0c056156920c489b7%5E%21/#F0

**Comment by jrodbx** [comment]
verifying example:

```
  @Test
  fun swipeRefreshAnimation() {
    val view = object : SwipeRefreshLayout(paparazzi.context) {
      override fun onAttachedToWindow() {
        viewTreeObserver.addOnPreDrawListener {
          println("animated: $drawingTime")
          true
        }
      }
    }.apply {
      isRefreshing = true
      addView(ListView(paparazzi.context))
    }
    paparazzi.gif(view, end = 5000L, fps = 60)
  }
```

**Comment by geoff-powell** [comment]
Nice, glad they fixed this in layoutlib 🎉
