### ISSUE TITLE
Custom path for snapshot image storages

### ISSUE THREAD

**Issue by tiansunsupernova** [cashapp/paparazzi#862]
Images are currently stored to `src/test/snapshots` by default. Is there any way to config to a custom path for storage. Thanks!

**Comment by TWiStErRob** [comment]
https://github.com/cashapp/paparazzi/pull/736 should solve this.

**Comment by tiansunsupernova** [comment]
@TWiStErRob  Thank you!

**Comment by TWiStErRob** [comment]
Might want to keep this open until fixed? (the PRs don't have an issue referenced)

**Comment by hd-bitingbit** [comment]
Hello @TWiStErRob,
It seems that the PR has been in draft state for almost a year. Any update? It would be great if we could have this feature in the library.

**Comment by TWiStErRob** [comment]
It's up to the author to propose the changes. (Also I'm not a maintainer, so I can't merge, even if it was ready.)
