### ISSUE TITLE
Missing JUnit XML report

### ISSUE THREAD

**Issue by multiholle** [cashapp/paparazzi#952]
**Description**
I can not find an XML report for the executed tests. This would be necessary for CI reports. Is there a way to enable XML report output?

gitlab requirements for reports:
https://docs.gitlab.com/ee/ci/testing/unit_test_reports.html

**Comment by jrodbx** [comment]
According to [Gradle Test task documentation](https://docs.gradle.org/current/userguide/java_testing.html#test_reporting), xml reporting is provided by default.

When I run `./gradlew sample:recordPaparazziDebug`, I see the XML reports generated under `sample/build/test-results/testDebugUnitTest` per test class.
