### ISSUE TITLE
Dynamically sized snapshot

### ISSUE THREAD

**Issue by matejdro** [cashapp/paparazzi#953]
Currently, Paparazzi only seems to support statically sized snapshot (e.g. snapshot width and height are fixed via device config). However, this means that taking a snapshot of a small composable (components such as a button) will result a huge blank screen with a tiny component on top.

Consequently, `maxPercentDifference` is practically required to be set to `0.0`, since most of the snapshot is just empty space and even completely changing the target composable would result in a small relative change to the image.

Could we add a flag to size snapshots dynamically to the target content (similar to how compose previews work in the editor)? Of course, if golden image's size mismatches new image, test would immediately fail.

**Comment by TWiStErRob** [comment]
Related #483, but I think #497 has implemented what you want:

```kotlin
Paparazzi(
    …,
    renderingMode = RenderingMode.SHRINK,
)
```

**Comment by matejdro** [comment]
That is exactly what I want, thanks!
