### ISSUE TITLE
Delta images break on dimension change with RenderingMode.SHRINK

### ISSUE THREAD

**Issue by ko-bra** [cashapp/paparazzi#964]
**Description**
When using RenderingMode.SHRINK: If the dimensions of a recorded image during verify are different from the dimensions of the golden image, the delta image may lack: 

- the diff image and/or
- parts of the actual and expected image.

**Steps to Reproduce**
1. Set the rendering mode to `RenderingMode.SHRINK`
2. Set up a test and `record` the golden image for a component
3. Change the test so that either
3.1  the width of the component is reduced, or
3.2 the height of a component is changed.
5. Run a `verify`

**Expected behavior**
The produced delta image file should contain
- the expected image
- the diff image
- the actual image

All of the above should be rendered in full size and be visible.

**Observed behavior**
- On width reduction: The _expected image_ overrides the _delta image_.
- On height change: Either the _actual_ or the _expected_ image is cut off in height.

**Potential cause**
See this excerpt of the function [assertImageSimilar(...)](https://github.com/cashapp/paparazzi/blob/8f69445ff1b157cab6bbc6202598dd99a2782b04/paparazzi/src/main/java/app/cash/paparazzi/internal/ImageUtils.kt#L98) of `ImageUtils`:

```
val imageWidth = Math.min(goldenImage.width, image.width)
val imageHeight = Math.min(goldenImage.height, image.height)
val width = 3 * imageWidth
val deltaImage = BufferedImage(width, imageHeight, TYPE_INT_ARGB)
```
After drawing the delta image in the middle, the expected and actual images are drawn:
```
g.drawImage(goldenImage, 0, 0, null)
g.drawImage(image, 2 * imageWidth, 0, null)
```
Due to tripling the width of the smaller _actual image_, the larger _expected image_ does not fit in its "slot" on the left and will overwrite the delta "slot".
On a height change, one of the images will be cropped because the height is set to the minimum height between the two images.

**Additional information:**
- Paparazzi Version: 1.2
- OS: macOS 13.1 (22C65) aarch64
- Compile SDK: 31
- Gradle Version: 7.5.1
- Android Gradle Plugin Version: 7.4.0

**Comment by jrodbx** [comment]
Fixed in #1122
