### ISSUE TITLE
verifyPaparazziDebug gradle task does not detect diff

### ISSUE THREAD

**Issue by FDELAHA24** [cashapp/paparazzi#968]
**Description**
When I record golden values for a `LinearProgressIndicator` with `StrokeCap.Square` using jetpack compose, the screenshot is saved.
But when I change the `strokeCap` value to `StrokeCap.Round` and I hit verifyPaparazziDebug the task completes successfully. 

**Steps to Reproduce**
1.Add the following test to your project : 
```
class LinearProgressPrimaryTest {
    @get:Rule
    val paparazzi = Paparazzi()

    @Test
    fun test() {
        paparazzi.snapshot { TestLinearProgressIndicator() }
    }
}

@Suppress("TestFunctionName")
@Composable
fun TestLinearProgressIndicator() {
    Box {
        LinearProgressIndicator(
            progress = 0.5f,
            modifier = Modifier.align(Alignment.Center).height(10.dp).fillMaxWidth(),
            color = Color.Blue,
            backgroundColor = Color.White,
            strokeCap = StrokeCap.Square
        )
    }
}
```

2.run the recordPaparazziDebug gradle task
3.change the `strokeCap` value from  `StrokeCap.Square` to `StrokeCap.Round`
4.run the verifyPaparazziDebug gradle task

**Expected behavior**
The task should fail and a delta image should be created

**Observed behavior**
The task completes successfully and no delta image is created

**Additional information:**
- Paparazzi Version: 1.3.0
- OS: mac OS 13.3.1 (22E261)
- Compile SDK: 33
- Gradle Version: 8.0
- Android Gradle Plugin Version: 8.0.2
- compose-compiler : 1.4.7
- compose-material : 1.4.3
- kotlin : 1.8.21

**Screenshots**
Here are the screenshot generated by the record for the 2 versions of strokeCap : 
![com example mylibrary_VitaminCircularProgressPrimaryTest_compose 2](https://github.com/cashapp/paparazzi/assets/48826368/2be2c057-1d74-4881-9d34-0eb410168fcf)

![com example mylibrary_VitaminCircularProgressPrimaryTest_compose](https://github.com/cashapp/paparazzi/assets/48826368/39a1b4d7-f3c4-4ff0-81fd-a0b1ad57e2ae)

**Comment by TWiStErRob** [comment]
The default diff is 0.1%, this is probably below that. Try setting `maxPercentDifference = 0.0` in the `Paparazzi` constructor.

**Comment by FDELAHA24** [comment]
Hi @TWiStErRob ! It's working with `maxPercentDifference = 0.0`. I'm closing the issue, sorry for bothering ^^
