### ISSUE TITLE
compose bottomsheet does not screenshot

### ISSUE THREAD

**Issue by rulogarcillan** [cashapp/paparazzi#974]
**Description**
Take a screenshot of a bottomsheet
**Steps to Reproduce**
Add a  bottomsheet in compose
**Expected behavior**
Get the screenshot of the modal

Problem
The problem is that as a bottomshet to be displayed has an animation where it appears after a second, the screenshot obtained is a completely white screen

**Comment by jrodbx** [comment]
@rulogarcillan thanks for the issue, however it's a bit sparse.  can you please provide a repro?  it's hard to know if this is a byproduct of how you set up the view or a true Paparazzi bug.

**Comment by xavijimenezmulet** [comment]
Same here:

`class ModalBottomSheetTest : BaseScreenshotTest() {

    @Test
    fun testModalBottomSheet() {
        paparazzi.snapshot {
            ModalBottomSheetTestCase()
        }
    }

    @OptIn(ExperimentalMaterial3Api::class)
    @Composable
    private fun ModalBottomSheetTestCase() {
        ModalBottomSheet(
            onDismissRequest = {}
        ) {
            Text(text = "Content")
        }
    }
}`

**Comment by siddh1004** [comment]
I'm facing the same issue. @jrodbx are we still looking into this.
`@OptIn(ExperimentalMaterial3Api::class)
    @Test
    fun launchOrgBottomSheet() {
        paparazzi.snapshot {
            val orgTreeItems = originalOrgTreeItems + childrenOrgItems
            ModalBottomSheet(
                onDismissRequest = {}
            ) {
                Text(text = "Content")
            }
        }
    }`

**Comment by leo-beliakov** [comment]
@jrodbx Any updates on this?

**Comment by geoff-powell** [comment]
This should be fixed with #1537. Try `1.3.5-SNAPSHOT` to confirm.
