### ISSUE TITLE
GIF verification support

### ISSUE THREAD

**Issue by sumitjat** [cashapp/paparazzi#978]
I was checking _GIF verification_ support which is not there in library at the moment , but there seems to be multiple Merge request raised to support for [same](https://github.com/cashapp/paparazzi/pulls?q=is:pr+is:open++gif). Do we have any plan to Merge those ?

**Comment by iujames** [comment]
This would be very useful for our project as well!

**Comment by jrodbx** [comment]
Closing as duplicate of #496
