### ISSUE TITLE
Decouple failure directory from system property for user.dir.

### ISSUE THREAD

**Issue by apkelly** [cashapp/paparazzi#987]
The failure directory is linked to the system property for the user.dir

```
  private val failureDir: File
    get() {
      val workingDirString = System.getProperty("user.dir")
      val failureDir = File(workingDirString, "out/failures")
      failureDir.mkdirs()
      return failureDir
    }
```

I'd like to be able to configure this via the `SnapshotVerifier` class. e.g.

```
    companion object {
        private val isVerifying: Boolean =
            System.getProperty("paparazzi.test.verify")?.toBoolean() == true

        // Place images in flavor specific sub-folders.
        val snapshotHandler = if (isVerifying) {
            SnapshotVerifier(
                maxPercentDifference = 0.1,
                rootDirectory = File("src/test/snapshots/${BuildConfig.FLAVOR_customer}"),
                failureDirectory = File("src/test/failures/${BuildConfig.FLAVOR_customer}")
            )
        } else {
            HtmlReportWriter(
                snapshotRootDirectory = File("src/test/snapshots/${BuildConfig.FLAVOR_customer}")
            )
        }
    }
```

**Comment by apkelly** [comment]
Also, I think it'd be great (if maybe redundant) to rename the `rootDirectory` parameter on the `SnapshotVerifier` to be `snapshotRootDirectory` just to match the `HtmlReportWriter`. Since these folders need to be the same, and there is an alternate `rootDirectory` parameter on the `HtmlReportWriter` class too, which may cause confusion.

**Comment by jrodbx** [comment]
Already fixed on master per https://github.com/cashapp/paparazzi/pull/935

**Comment by apkelly** [comment]
@jrodbx the failure directory although decoupled (thanks), is still hard-coded to a single location. Would you like me to raise a new issue to request the ability to configure the directory as per my example e.g. based on build flavor?
