### ISSUE TITLE
Snapshot file name contains characters invalid on Windows

### ISSUE THREAD

**Issue by elliot-nelson** [cashapp/paparazzi#989]
**Description**

If your snapshot State has functions in it, it gets "rendered" as text into the filename in a way that makes the file path invalid on Windows. This fails the test, or works on MacOS and then fails later for Windows devs who try to pull your branch in git.

**Steps to Reproduce**

As an example, you might have a test that looks something like this:

```kotlin
    fun `Given state is Standard Then Button with no icon is displayed`() {
        var contentDescription = ""
        val text = "Browse"
        var i = 0
        with(composeTestRule) {
            setContent {
                AppTheme {
                    contentDescription = stringResource(id = "browse")
                    PrimaryButtonRouter(
                        state = Standard(
                            text = PrimaryButtonTextState.Browse,
                            onClick = { i++ },            // <------ problem
                            isFocused = false,
                            onFocusChanged = {},        // <------- problem
                        )
                    )
                }
            }
            onNodeWithContentDescription(contentDescription).assertDoesNotExist()
            onNodeWithText(text).assertIsDisplayed().performClick()
            assertEquals(1, i)
        }
    }
```

The property `onClick` for example is a function, which results in this filename:

```
...../x.x.x.x.snapshot.test_PrimaryButtonsTest_primaryButtonTest[Play(text=Watch, isFocused=false, onClick=() -> kotlin.Unit, onFocusChanged=(kotlin.Boolean) -> kotlin.Unit)].png
```

**Expected behavior**

If the generated filename for a snapshot contains invalid characters on any platform (for example, `>` and `:`), perhaps they could be stripped down to underscores.

(In fact, ideally, _all_ nonstandard characters -- including spaces, left and right parens, and left and right brackets, could be stripped down to underscores, to ensure broad compatibility in filenames.)

**Additional information:**
- Paparazzi Version: 1.2.0
- OS: Windows 10 Pro
- Compile SDK: 
- Gradle Version: 7.4.1
- Android Gradle Plugin Version: 4.1.1.4

**Comment by jrodbx** [comment]
Some questions:
1) Have you tried with Paparazzi 1.3.0?
2) I don't see a call to Paparazzi.snapshot; is that the type of `composeTestRule`?
3) Is your actual test (i.e., maybe one that serves as the basis of this test?) using TestParameterInjector and passing the onClick as a TestParameter?

Otherwise, I don't see how the filename would result as it does, given how Snapshot determines the file name by default: https://github.com/cashapp/paparazzi/blob/master/paparazzi/src/main/java/app/cash/paparazzi/Snapshot.kt#L31

Can you share a repro/sample?

**Comment by jrodbx** [comment]
@elliot-nelson any update here?

**Comment by jrodbx** [comment]
Closing due to lack of response.  Please re-open with a sample project and we'll be happy to take a look.
