### ISSUE TITLE
Changing the content of the composable does not fail the test

### ISSUE THREAD

**Issue by coroutineDispatcher** [cashapp/paparazzi#999]
**Description**
Sorry if this is an intended behaviour. I'm not 100% sure if this is a bug.
Changing the content of the same composable does not fail the test.

**Steps to Reproduce**
Create this composable:

```kotlin
@Composable
fun Greeting(name: String, modifier: Modifier = Modifier) {
    Text(
        text = "Hello $name!",
        modifier = modifier
    )
}
```

Create the reference image with: 

```kotlin
class GreetingsScreenTest {

    @get:Rule
    val paparazzi = Paparazzi(
        deviceConfig = PIXEL_5,
        theme = "android:Theme.Material.Light.NoActionBar"
    )

    @Test
    fun `greetings screen should say Hello Android`() {
        paparazzi.snapshot {
            Greeting(name = "Android")
        }
    }
}
```

and run: `./gradlew module:recordPaparazziDebug`

Then change the composable parameter from "Android" to "Whatever".

```
@Test
    fun `greetings screen should say Hello Android`() {
        paparazzi.snapshot {
            Greeting(name = "Whatever")
        }
    }
```

run `./gradlew module:verifyPaparazziDebug` (or if build folder not there, `./gradlew module:testDebug`)

Test does not fail even though the content of the same composable is different.

**Expected behavior**
Here I am not 100% sure if this is the intended behaviour that's why I created this issue.

**Additional information:**
- Paparazzi Version: 1.3.0
- OS: Mac
- Compile SDK: 33
- Gradle Version: 8.0
- Android Gradle Plugin Version: 8.0.0

**Screenshots**
ref image
<img width="298" alt="Screenshot 2023-07-16 at 11 32 33" src="https://github.com/cashapp/paparazzi/assets/31472273/995cac1a-58ef-490d-a9fa-c0ca67faa39b">

The one in the build folder

<img width="289" alt="Screenshot 2023-07-16 at 11 33 03" src="https://github.com/cashapp/paparazzi/assets/31472273/ac614514-a40c-49f9-ab0a-8e1b768c7428">

I also have the demo in Github if you want to directly try it there: https://github.com/coroutineDispatcher/paparazzi_demo

**Comment by TWiStErRob** [comment]
Probably https://github.com/cashapp/paparazzi/issues/968#issuecomment-1615253837

**Comment by jrodbx** [comment]
Can you check if changing maxPercentDifference to 0.0 works?

**Comment by coroutineDispatcher** [comment]
When you add this parameter, the test fails (assuming correct behaviour)

**Comment by jrodbx** [comment]
Yep, that's correct behavior!
